### ISSUE TITLE
DelimitedTextFile trim file incorrectly around rebalance

### ISSUE THREAD

**Issue by yyejun** [pinterest/secor#101]
DelimitedTextFile assumed LogFilePath's offset is the starting offset, and entire file is continuous stream. 

First problem will be a rebalance happened after datetime partition switch, but this doesn't happen very often at same time with a rebalance event.

Second situation is an old thread picked a topic again after a period time, it will still use previous committed offset as filename which can be days ago.

**Comment by pgarbacki** [comment]
Yes, this is a known issue. https://groups.google.com/forum/#!searchin/secor-users/Praveen/secor-users/-w7jvfDNBEs/80bM-Ue4fNAJ

@lefthandmagic any chance you could attempt a fix any time soon? Otherwise, we should probably remove this parser to avoid distribution of the buggy code.

**Comment by lefthandmagic** [comment]
Hey Pawel.. I'm unfortunately travelling and will be out for a month :( 

Also - we moved away from using this - as it was strictly used for legacy purposes. We moved on to sequence files and parquet now. Feel free to remove it actually. I think this needs a revisit to do it right, and there is no real nice way to do this correctly, as we need to inject the offset in each row.

**Comment by yyejun** [comment]
I guess I will work on fixing this. I plan to store both offset and message length in a secondary file just for the purpose of trimming.
