### ISSUE TITLE
Retry mechanism in case of upload failure

### ISSUE THREAD

**Issue by ms309** [pinterest/secor#1034]
HadoopS3Uploader:
Observed that in case of upload failure it throws the exception 
 final Future<?> f = executor.submit(new Runnable() {
            @Override
            public void run() {
                try {
                    FileUtil.moveToCloud(localLogFilename, logFileName);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

shouldn't there be a retry mechanism in case upload is not successful.

**Comment by HenryCaiHaiying** [comment]
If FileUtil.moveToCloud didn't do the retry, you can add the retry.   Buy
eventually it will still throw Exception when all retries failed.  I don't
think the data will loss, on that exception secor would stop and the next
run will re-process those messages.
