### ISSUE TITLE
Twitter jars not getting downloaded

### ISSUE THREAD

**Issue by piyuverma** [pinterest/secor#1051]
Build failure while fetching twitter jars.

**Comment by HenryCaiHaiying** [comment]
Sent a request to gcs-maven-mirror@googlegroups.com

**Comment by HenryCaiHaiying** [comment]
It seems the folks at GCS mirror is unwilling to sync the jars from Twitter
maven.

Also opened a support ticket to Travis to see whether they can stop
mirroring all repos to GCS.

**Comment by HenryCaiHaiying** [comment]
If Travis folks is unwilling to revert their change, we probably have to
use our own mirrors to disable GCS mirror as suggested here:
https://travis-ci.community/t/disable-google-maven-central/5301

**Comment by sreeram26** [comment]
Do we have any updates on this?

**Comment by HenryCaiHaiying** [comment]
No updates on Travis side.

If you have time, you can prepare a PR to add a setting.xml which defines
another mirror override to override the twitter maven repo back to twitter
(instead of Google mirror)

**Comment by sreeram26** [comment]
Sorry I don't quiet follow. 
I see https://maven.twttr.com/com/twitter/maven-finagle-thrift-plugin/0.0.9/ also missing the corresponding jar?
Same case with most other repositories. What would be the exact change in settings.xml which would solve this?

**Comment by HenryCaiHaiying** [comment]
Take a look at how they specify repo mirror in settings.xml (essentially
cancelled off google's mirror), we need this for twitter's maven repo
mirror.

ksclarke <https://travis-ci.community/u/ksclarke>
2  <https://travis-ci.community/t/disable-google-maven-central/5301#>
Oct 7 <https://travis-ci.community/t/disable-google-maven-central/5301/2>

I want this too. Google’s mirror of Maven Central is taking too long to
sync with the upstream.

*Update:* To get around the Google mirror, you can set the real Maven
central as a mirror in a settings.xml file and pass that to the mvn command
with -s. For an example:
https://github.com/ksclarke/vertx-super-s3/blob/master/src/test/resources/settings.xml#L21
5
<https://github.com/ksclarke/vertx-super-s3/blob/master/src/test/resources/settings.xml#L21>
 and https://github.com/ksclarke/vertx-super-s3/blob/master/.travis.yml#L17
6 <https://github.com/ksclarke/vertx-super-s3/blob/master/.travis.yml#L17>

**Comment by sreeram26** [comment]
I tried that
```
[ERROR] Failed to execute goal on project secor: Could not resolve dependencies for project com.pinterest:secor:jar:0.29-SNAPSHOT: The following artifacts could not be resolved: com.hadoop.gplcompression:hadoop-lzo:jar:0.4.16, com.twitter.common.zookeeper:lock:jar:0.0.7: Could not find artifact com.hadoop.gplcompression:hadoop-lzo:jar:0.4.16 in maven-central (http://repo1.maven.org/maven2) -> [Help 1]
```
As these are not present in maven central's repo too see http://repo1.maven.org/maven2/com/hadoop/compression/hadoop-gpl-compression/0.1.0/

**Comment by HenryCaiHaiying** [comment]
Those jars are only in twitter's maven repo

How does your PR look like?

**Comment by sreeram26** [comment]
Yes exactly, and the twitter's maven repo seems to miss the corresponding jars.
One example is 
https://maven.twttr.com/com/hadoop/gplcompression/hadoop-lzo/0.4.20/

Raised https://github.com/twitter/hadoop-lzo/issues/140, but no updates so far. Similarly for all of the other jars available only in twitter's maven repo.

**Comment by HenryCaiHaiying** [comment]
It looks like 0.4.16 hadoop-lzo are still there:

https://maven.twttr.com/com/hadoop/gplcompression/hadoop-lzo/0.4.16/

**Comment by piyuverma** [comment]
No, for 0.4.16 hadoop-lzo also, just the .pom files and md5 and sha1 hash files are there but not the actual .jar file.

**Comment by msilvestre** [comment]
Is there any workaround for this issue?

**Comment by guillem** [comment]
Do we know what's going on with Twitter? Is this a mistake or they've removed the files for good?
Since they're still publishing the hashes, can someone who still has the files at least share them please, so we can manually make the compilation work? Thanks.

**Comment by piyuverma** [comment]
I have all the jars except for the finagle plugin, i tried commenting out the plugin in pom and with installing all the jars locally in order to get away with the compile time build error. The build succeeded, but got NoClassDefFoundError at runtime for one of the Class present in Twitter jar. However, that class was present at compile time.

**Comment by piyuverma** [comment]
Please download jars here https://drive.google.com/open?id=1WpVlxvJZ5Ip-o9zIg3Q8QsIzormrdzTy

**Comment by piyuverma** [comment]
Please download jars here https://drive.google.com/open?id=1WpVlxvJZ5Ip-o9zIg3Q8QsIzormrdzTy

**Comment by msilvestre** [comment]
Any news regarding this issue?

**Comment by HenryCaiHaiying** [comment]
Got some feedback from https://gitter.im/twitter/finagle, they asked to upgrade finagle-maven-plugin to scrooge-maven-plugin

**Comment by sreeram26** [comment]
There are other dependencies from twitter like https://maven.twttr.com/com/twitter/common/zookeeper/lock/ what are your plans for that?

**Comment by HenryCaiHaiying** [comment]
One at a time, I am upgrading maven-plugin first, to see if this PR can pass through build:
https://github.com/pinterest/secor/pull/1087

**Comment by HenryCaiHaiying** [comment]
Looks like we passed maven plugin block, now it's stuck at:

The following artifacts could not be resolved: com.hadoop.gplcompression:hadoop-lzo:jar:0.4.16, com.twitter.common.zookeeper:lock:jar:0.0.7, com.twitter.common.zookeeper:client:jar:0.0.7, com.twitter.common:net-util:jar:0.0.29, com.twitter.common:collections:jar:0.0.34, com.twitter.common:quantity:jar:0.0.30, com.twitter.common:base:jar:0.0.38, com.twitter.common:util-system-mocks:jar:0.0.26:

**Comment by HenryCaiHaiying** [comment]
Almost all twitter.common jars are pulled in because of com.twitter.common.zookeeper:lock:jar:0.0.7, twitter people asked us to upgrade to finagle-serverset

**Comment by HenryCaiHaiying** [comment]
Actually apache.curator package is probably more appropriate for zookeeper locks

**Comment by HenryCaiHaiying** [comment]
Made another commit to use apache.curator: https://github.com/pinterest/secor/pull/1087

Now we are only missing one jar: com.hadoop.gplcompression:hadoop-lzo:jar:0.4.16,

And this is pulled from this path:

[INFO] +- org.apache.parquet:parquet-protobuf:jar:1.9.0:compile
[INFO] |  \- com.twitter.elephantbird:elephant-bird-core:jar:4.4:compile
[INFO] |     +- com.twitter.elephantbird:elephant-bird-hadoop-compat:jar:4.4:compile
[INFO] |     +- com.googlecode.json-simple:json-simple:jar:1.1:compile
[INFO] |     \- com.hadoop.gplcompression:hadoop-lzo:jar:0.4.16:compile

**Comment by HenryCaiHaiying** [comment]
Made one more fix in pom.xml to get rid of the dependency on hadoop-lzo, let's see how far the build is going this time

**Comment by HenryCaiHaiying** [comment]
Make another fix: https://github.com/pinterest/secor/pull/1090

Looks like the build is working now.

**Comment by guillem** [comment]
Thank you guys :)
