### ISSUE TITLE
Does Secor rebalacing lead to missing partitions?

### ISSUE THREAD

**Issue by suminb** [pinterest/secor#1130]
My team has been using Secor for Kafka log persistence for a few months so far. Things work mostly okay, however we have noticed some strange phonomenon. To illustrate the situation precisely, let me list out some facts:

* We have about 30 Kafka topics that Secor consumes (mostly low-traffic topics with a few very busy topics).
* Each topic has anywhere between 5 and 50 partitions.
* We have two AWS EC2 instances (`c4.xlarge` type) running a Secor process with the identical consumer group name.
    * In such cases, as far as I understand, Secor automatically distributes partitions for each Secor process. Please let me know if I misunderstood this part.
* There have been multiple scaling in/out of Secor instances (not Kafka rebalancing) over the course of the past few months.
* We found at least one problematic topic that Secor failed to consume from all partitions. We will call this topic `topic1` for simplicity.

I'm not entirely sure how exactly this happened, but one day I have noticed that Secor is entirely missing some of the partitions for `topic1` as shown in the following snapshot from an ostrich stats page.

```
secor.modification_age_sec.topic1.[0].16: 234
secor.modification_age_sec.topic1.[10].21: 2873
secor.modification_age_sec.topic1.[11].21: 3152
secor.modification_age_sec.topic1.[12].22: 929
secor.modification_age_sec.topic1.[13].22: 3286
secor.modification_age_sec.topic1.[14].16: 3653
secor.modification_age_sec.topic1.[15].16: 3664
secor.modification_age_sec.topic1.[16].17: 3713
secor.modification_age_sec.topic1.[17].17: 3713
secor.modification_age_sec.topic1.[18].18: 3709
secor.modification_age_sec.topic1.[19].18: 3709
secor.modification_age_sec.topic1.[1].16: 1176
secor.modification_age_sec.topic1.[1].17: 3632
secor.modification_age_sec.topic1.[20].19: 3651
secor.modification_age_sec.topic1.[21].19: 3655
secor.modification_age_sec.topic1.[22].20: 3718
secor.modification_age_sec.topic1.[23].20: 3721
secor.modification_age_sec.topic1.[24].21: 3613
secor.modification_age_sec.topic1.[25].21: 3626
secor.modification_age_sec.topic1.[26].22: 3664
secor.modification_age_sec.topic1.[27].22: 3664
secor.modification_age_sec.topic1.[2].16: 3669
secor.modification_age_sec.topic1.[2].17: 1868
secor.modification_age_sec.topic1.[2].18: 3670
secor.modification_age_sec.topic1.[3].17: 489
secor.modification_age_sec.topic1.[3].19: 3699
secor.modification_age_sec.topic1.[4].18: 1270
secor.modification_age_sec.topic1.[4].20: 3601
secor.modification_age_sec.topic1.[5].18: 142
secor.modification_age_sec.topic1.[5].21: 3637
secor.modification_age_sec.topic1.[6].19: 139
secor.modification_age_sec.topic1.[6].22: 3685
secor.modification_age_sec.topic1.[7].19: 2625
secor.modification_age_sec.topic1.[8].20: 1155
secor.modification_age_sec.topic1.[9].20: 1155

secor.modification_age_sec.topic1.[43].16: 1070
secor.modification_age_sec.topic1.[44].17: 185
secor.modification_age_sec.topic1.[45].18: 1343
secor.modification_age_sec.topic1.[46].19: 3292
secor.modification_age_sec.topic1.[47].20: 2221
secor.modification_age_sec.topic1.[48].21: 1557
secor.modification_age_sec.topic1.[49].22: 1876
```

Partition 28-42 (a total of 15 partitions) are missing.

I was wondering whether this is something that may happen during Secor rebalancing.

**Comment by HenryCaiHaiying** [comment]
Probably the secor worker who gets assigned those partitions have problems,
turn on more debug level logging categories can find out those problems.
Or on the zookeeper side I think you can also find the partition to worker
mapping.

**Comment by suminb** [comment]
Thanks for your quick response. I tried to re-produce this error so that I could provide more details, but I was not able to do so. I'll look into the logs and the zookeeper and close this issue for now.

**Comment by ms309** [comment]
we are observing similar behavior, wherein intermittently secor loses ownership on few partitions.
Took a thread dump during the same time, analysis shows the possible deadlock state in that scenario:
few lines:
>>>>
0x0000000375332de0Object**Possible deadlock** | Held by secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189_watcher_executorawaiting notification on [ 0x0000000377f1e898 ] , holding [ 0x0000000375332de0 ]2 thread(s) waiting to take lock Thread-153 Thread-153
-- | --
0x0000000377f1d368ReentrantLock$NonfairSync**Possible deadlock** | Held by ConsumerFetcherThread-secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-0-212awaiting notification on [ 0x0000000375345078 ] , holding [ 0x0000000377f1d368 ]1 thread(s) waiting for notifcation: secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-leader-finder-thread
0x0000000377f1e378ReentrantLock$NonfairSync**Possible deadlock** | Held by ConsumerFetcherThread-secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-0-212awaiting notification on [ 0x0000000375345078 ] , holding [ 0x0000000377f1e378 ]1 thread(s) waiting for notifcation: secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-leader-finder-thread
<<<
In this leader finder thread is indefinitely waiting for resource on consumer fetcher thread
