### ISSUE TITLE
secor loses partition ownership during rebalancing  

### ISSUE THREAD

**Issue by ms309** [pinterest/secor#1173]
In case we are adding new topic it triggers rebalance in consumer group.
partition assignment strategy: round robin
and once rebalancing is done, secor is not able to get ownership for all the partitions in that consumer group.
This behavior is intermittent and reproducing it is not easy.
Took a thread dump during the time when partition ownership was missing.
I shows that there is a possible deadlock.
Strangely when we stop all the instances in the consumer group and start it again it works.
Not sure why synchronization is creating issue in running service during rebalancing
thread dump lines:
>>>

0x0000000375332de0ObjectPossible deadlock | Held by secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189_watcher_executorawaiting notification on [ 0x0000000377f1e898 ] , holding [ 0x0000000375332de0 ]2 thread(s) waiting to take lock Thread-153 Thread-153
-- | --
0x0000000377f1d368ReentrantLock$NonfairSyncPossible deadlock | Held by ConsumerFetcherThread-secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-0-212awaiting notification on [ 0x0000000375345078 ] , holding [ 0x0000000377f1d368 ]1 thread(s) waiting for notifcation: secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-leader-finder-thread
0x0000000377f1e378ReentrantLock$NonfairSyncPossible deadlock | Held by ConsumerFetcherThread-secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-0-212awaiting notification on [ 0x0000000375345078 ] , holding [ 0x0000000377f1e378 ]1 thread(s) waiting for notifcation: secor-consumer-awz_s3_ip-172-31-43-12.ap-southeast-1.compute.internal_2491_189-leader-finder-thread
<<<
leader finder is waiting indefinitely for consumer fetcher.

**Comment by HenryCaiHaiying** [comment]
The issue might be in the Kafka consumer rebalancing code, which Kafka version are you using?
