### ISSUE TITLE
Secor copying files under inconsistent file path

### ISSUE THREAD

**Issue by oconryaa** [pinterest/secor#1217]
When copying files from kafka to our hadoop nodes secor is pre-pending files under a randomly generated directory following the format <dynamic_number>/<kafka-topic>/...

I would like to remove the <dynamic_number> such that I can always find my data stored under a consistent path for querying data. So far the only fix I have found is by removing lines 151-153 in LogFilePath.java:

if (mPrefix != null && mPrefix.length() > 0) {
//     elements.add(mPrefix);
}

Is there a way to handle this without a code change?

**Comment by HenryCaiHaiying** [comment]
Can you give an example on the current file path secor was generating on your file system?
