### ISSUE TITLE
Secor does not handle topic deletion gracefully

### ISSUE THREAD

**Issue by fabeschan** [pinterest/secor#126]
When a topic gets deleted, the consumer offset for secor stays at whatever it was before, and causes these sorts of ERRORs:

2015-08-27 21:53:50,911 [ConsumerFetcherThread-secor_consumer1231423_e25fd1c7e266_1_12-0-1] (kafka.utils.Logging$class:97) ERROR [ConsumerFetcherThread-secor_consumer1231423_e25fd1c7e266_1_12-0-1], Current offset 15 for partition [test.endtoendtest.category01,0] out of range; reset offset to 0

However, it doesn't resolve itself. In the mean time, a lot of errors get produced on the kafka end, since secor is requesting out of range offsets or non-existent topics.

I was hoping auto.offset.reset=min would help but looks like it has no effect.

**Comment by HenryCaiHaiying** [comment]
Would restart secor help to remove the deleted topic?

If not, would specify some regex expression on topicFilter work to exclude that topic?

Kafka also have a concept of Blacklist (we only used its Whitelist), you can extend secor to use the Kafka's Blacklist to exclude topics (and send us the PR).

**Comment by fabeschan** [comment]
Hi henry,
Just tried restarting secor; doesn't seem to have an effect. 

Filtering out the topic probably works, but it seems like a bandaid fix, and requires explicit input. I wonder how much work it would be to have secor fix its consumer group offsets whenever it encounters this sort of situation.

**Comment by HenryCaiHaiying** [comment]
This seems to me more like a kafka bug (the high level consumers is still
consuming from a deleted topic), if you put more work in secor to handle
deleted topic, this sounds kludge to me.

Kafka topic deletion is usually not a common event in a production system,
that's why I suggest using topicFilter (or add support for Blacklist) for
those deleted topics, this only needs to happen once in a long while.

**Comment by HenryCaiHaiying** [comment]
fabeschan, I am closing this one.  Let me know whether you want to play with topic filters.
