### ISSUE TITLE
Support persistence to HDFS instead of S3

### ISSUE THREAD

**Issue by SEJeff** [pinterest/secor#129]
For use cases where kafka runs entirely behind corp firewalls, and AWS isn't an option, it would be wonderful to use Secor. Would it be possible to persist things onto hdfs instead of s3 as an option?

Thanks!

**Comment by HenryCaiHaiying** [comment]
This is very legitimate use case.  I think adding the support for HDFS ingestion is not hard at all.

In Uploader.java, currently this is hard-coded as:
        String s3Prefix = "s3n://" + mConfig.getS3Bucket() + "/" + mConfig.getS3Path();

If you make the destination filesystem a configurable parameter, that probably would just work because underlying we are using HDFS's FileSystem.moveFromLocalFile method to do the S3 file move anyway.

**Comment by banks** [comment]
@SEJeff out of interest, any reason you can't just use one of the other tools like linkedin's Camus (or the newer Gobblin: https://github.com/linkedin/gobblin)?

Not saying it's an invalid request for Secor to support that as an option, but the biggest selling point of Secor for our use case is that it ISN'T tied to HDFS/Hadoop which we don't use. I seem to recall finding at least 3 or 4 relatively mature looking alternatives that all assumed you have HDFS/MapReduce cluster to execute on.

See "Hadoop Integration" here: https://cwiki.apache.org/confluence/display/KAFKA/Ecosystem

**Comment by SEJeff** [comment]
Yeah Camus and Gobblin have a lot more requirements and aren't as straightforward as secor. Also, Camus expects you to write your decoding logic and whatnot in Java. Not that it isn't entirely doable, but isn't preferable for my use case. I'm honestly unimpressed with the confluent tools for this.

Of the various kafka mirroring tools, Secor, to me, is one of the better ones from a design standpoint. I would like to be able to use it in an environment that doesn't use any cloud services whatsoever. We do have a large-ish hdfs install and I was hoping we could use that.

If you fundamentally disagree, feel free to close this issue. It would be really nice to use Secor vs other solutions however.

**Comment by HenryCaiHaiying** [comment]
Jeff,

If you want to explore, you can definitely add a HDFSUploader for secor.
We use Hadoop's FileSystem object to work with sequence file uploading, it
should be quite straightforward to have the local sequence file uploading
to HDFS.

**Comment by skanda83** [comment]
Jeff,

I was able to make secor push files to HDFS just by making the following changes:

1. Add hadoop-client dependency to pom.xml
2. Use secor.s3.filesystem=hdfs
3. Use secor.s3.bucket=<namenode-host>:<8020>/dir_path
