### ISSUE TITLE
Describing Secor group in Kafka does not showing information

### ISSUE THREAD

**Issue by YakobovLior** [pinterest/secor#1332]
Hello,
I wanted to ask, how come when I run this command, I cannot see the offset for each topic Secor is backing up?

[root@aws-elk-kafka1 ~]# kafka-consumer-groups.sh --bootstrap-server 10.128.115.237:9092 --describe --group secor-new
Consumer group 'secor-new' has no active members.

The consumer group name I have configured is **secor-new** and the process is stopped now, that is why it complains for no active members.

Thanks,
Lior

**Comment by HenryCaiHaiying** [comment]
I think by default, secor stores the consumer offset in ZK, that might be
why the consumer group command cannot see it.  Are you using kafka-2.0.0
profile during maven build?

**Comment by YakobovLior** [comment]
hey @HenryCaiHaiying,
Thanks for the answer, actually I didn't run the maven build, my colleague ran it quite a while ago and we don't remember if we used Kafka-2.0.0 profile..
I believe we do because our Kafka cluster version is 2.0.0.

Is there a way to check it after the build? If not I can rebuild and verify.
Plus, can you share an example of retrieving consumer offsets from the ZooKeeper?

Thank you,
Lior

**Comment by HenryCaiHaiying** [comment]
You can check your secor.properties file, if you see the following, you are
using kafka-2.0.0 profile during maven build:

kafka.message.iterator.className=com.pinterest.secor.reader.SecorKafkaMessageIterator


For zookeeper access, you can use zkCli.sh (shipped with zookeeper), you
can use the get/list command inside that program (there are many
documentation/examples on the internet).  There are also UI tool built on
top of ZK, e.g.
https://www.idata.co.il/2018/07/a-day-at-the-zoo-graphic-uis-for-apache-zookeeper/

**Comment by YakobovLior** [comment]
Hey @HenryCaiHaiying ,
I saw the configuration so I am using kafka-2.0.0.

Regading the Zookeeper, I managed to see the offsets with the Zookeeper CLI.
I do have a question though, is it possible to change the default and tell Secor to store offsets in Kafka instead of Zookeeper? 
We need this because we need to have the ability to reset offsets for the Secor consumer group in case we need to change the current position.

Thanks,
Lior

**Comment by HenryCaiHaiying** [comment]
To reset the consumer offsets in ZK, ZK CLI (or open source UI tool) can do
that as well.

To store the offsets in both ZK and Kafka, you can use the following
parameters:

kafka.dual.commit.enabled=true

kafka.offsets.storage=kafka

**Comment by YakobovLior** [comment]
Hey @HenryCaiHaiying ,
thanks for these details, very helpful!

Regards,
Lior
