### ISSUE TITLE
Kafka topics filter and blacklist usage issues

### ISSUE THREAD

**Issue by YakobovLior** [pinterest/secor#1333]
Hello,

I'm having issues with setting up the following configuration for Kafka topics to back up.
I want to have the ability to run Secor as follows:

secor.kafka.topic_filter=.* (the entire existing topics)
secor.kafka.topic_blacklist=topic1,topic2,topic3,topic4... (list of topics that will be excluded).

This configuration is not working though, what am I missing?
Are there any exmaples for the blacklist configuration usage?

Thanks,
Lior

**Comment by HenryCaiHaiying** [comment]
Are your using profile kafka-2.0.0 during maven build?  I think for
kafka-2.0.0, you might need to use the kafka new consumer property:

kafka.new.consumer.topic.list=


Take a look at the latest src/main/config/secor.common.properties

**Comment by YakobovLior** [comment]
Hey @HenryCaiHaiying,
I'm using the kafka-2.0.0 profile.

I used this configuration and it seems to work well, it reads only the topics I have specified.
On the other hand, if I can use blacklist instead of the topics list it will be more convenient. 
Does the blacklist as well works with kafka-2.0.0, similar to the topics list, with commas seperation?

Thanks,
Lior

**Comment by HenryCaiHaiying** [comment]
Looks like you can do some filtering: if kafka.new.consumer.topic.list is
empty, it will use secor.kafka.topic_filter

https://github.com/pinterest/secor/blob/8b0ac6e5a05a45543297a321c3e3c894d8a05046/src/main/java/com/pinterest/secor/reader/SecorKafkaMessageIterator.java#L144

public void subscribe(RebalanceHandler handler, SecorConfig config) {
    ConsumerRebalanceListener reBalanceListener = new
SecorConsumerRebalanceListener(mKafkaConsumer, mZookeeperConnector,
getSkipZookeeperOffsetSeek(config),
config.getNewConsumerAutoOffsetReset(), handler);
    ;

    String[] subscribeList = config.getKafkaTopicList();
    if (subscribeList.length == 0 || Strings.isNullOrEmpty(subscribeList[0])) {
        mKafkaConsumer.subscribe(Pattern.compile(config.getKafkaTopicFilter()),
reBalanceListener);
    } else {
        mKafkaConsumer.subscribe(Arrays.asList(subscribeList),
reBalanceListener);
    }
}
