### ISSUE TITLE
Enhance secor's metrics monitoring library, integration with more metrics backend

### ISSUE THREAD

**Issue by HenryCaiHaiying** [pinterest/secor#1341]
Currently secor's metrics monitoring relies on Twitter's Ostrich library which is already deprecated.  There are many stats/metrics collection libraries and backend systems on the market (e.g. StatsD, Promethus, Graphite, Datadog, Influx etc).

A good way to support integration with those metrics collection system is using Micrometer facade (micrometer.io) which provides a common interface and prebuilt integration with most popular metrics systems.

**Comment by HenryCaiHaiying** [comment]
@gmcoringa FYI

**Comment by gmcoringa** [comment]
Very good, thanks for adding this so fast
