### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by Roguelazer** [pinterest/secor#1393]
We've been running 0.27 for a while and I was doing a new build when I discovered that 0.27 no longer builds because of some version issue deep in the maven output. Master builds, but I have no idea if it's stable. Any plans to do a new release soon?

**Comment by HenryCaiHaiying** [comment]
We can cut a 0.28 release, there are several fixes and mini-features in the
latest code.

**Comment by HenryCaiHaiying** [comment]
0.28 version is cut and pushed to maven central, take a look to see whether that solves the problem.  Starting 0.28, we flipped to default build profile to kafka-2.0.0 (kafka 0.10.2 was deprecated)
