### ISSUE TITLE
UnsupportedOperationException fatal error when schema does not match 

### ISSUE THREAD

**Issue by ajwootto** [pinterest/secor#1505]
Hello, we are using Secor to parse JSON events using the JsonMessageParser, outputting to ORC files.

We encountered a fatal error the other day with an invalid event being present in the source topic, which contained a matching key name but had a different data type. The result was that the reader successfully parsed the message, but the writer failed and caused the following error:

![image](https://user-images.githubusercontent.com/1740731/89462889-1cd5ba80-d73c-11ea-824f-817cd362e50f.png)

It seems based on the implementation in [Consumer.java](https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/consumer/Consumer.java#L252), the intention is for Secor to skip messages that can't be parsed with a warning, but any write errors are rethrown. This caused Secor to get stuck on this one bad event and hold up the whole partition. Is this behaviour intentional or should it prevent a mismatch between reader and writer formats like this?

**Comment by HenryCaiHaiying** [comment]
Looking at Consumer code, looks like we skip the message when the message cannot be read or when the message cannot be parsed, so we should do the same when the message cannot be written.  @ajwootto I think you can submit a PR to skip the message when the message encountered the error during write.
