### ISSUE TITLE
offsetparser + date timestructure in s3

### ISSUE THREAD

**Issue by damaex17** [pinterest/secor#151]
Is it possible to use the system time of the upload to generate a s3 date structure instead of parsing messages to extract a timestamp there?

**Comment by HenryCaiHaiying** [comment]
You can provide a custom MessageParser which will return the time partition
based on system time instead of looking inside the message.

**Comment by pgarbacki** [comment]
It is possible (you can simply implement a custom message parser) but it is highly discouraged. If you use system time, you will break the consistency guarantees and will possibly introduce duplicate messages. Secor operates under the assumption that message->s3 path mapping is deterministic.
