### ISSUE TITLE
Occasional Unit test failures due to PowerMock

### ISSUE THREAD

**Issue by jonathan-stein** [pinterest/secor#1686]
`FileReaderWriterFactoryTest#mockDelimitedTextFileWriter` will occasionally have issues when trying to mock the FileSystem class. These issues appear to be the same as the documented issue in `FileReaderWriterFactoryTest#mockSequenceFileWriter`.

`Caused by: java.lang.IllegalStateException: Failed to transform class with name org.apache.hadoop.fs.FileSystem$Cache. Reason: org.apache.hadoop.fs.FileSystem$Cache$Key class is frozen`

**Comment by HenryCaiHaiying** [comment]
Will you be able to make the fix similar to

49f56938f7a987511d278ef7d1965cb27839a1e0?
