### ISSUE TITLE
No change in file format even though the configuration is edited

### ISSUE THREAD

**Issue by anishmashankar** [pinterest/secor#169]
I have edited the configuration file to change the output format to .gz, but the backup is still done in the binary key-value format. Here is a snippet my configuration file:
```
# To set a custom file extension set this to a valid file suffix, such as
# '.gz', '.part', etc.
secor.file.extension='.gz'
```
P.S. The aim is to have a readable file encoded in a format that can be read by another program for the backups done by secor.

**Comment by jgagnon1** [comment]
This configuration only seem to be used in `PartitionFinalizer` https://github.com/pinterest/secor/blob/ea4188af7c0843e28003d6cca451c93b0197db7f/src/main/java/com/pinterest/secor/parser/PartitionFinalizer.java#L58

The extension has nothing to do with the readable nor the file encoding. However if you want the Secor backup files to has the gz extension and actually be gzipped just use this configuration;
`secor.compression.codec=org.apache.hadoop.io.compress.GzipCodec`

**Comment by anishmashankar** [comment]
One of the output formats,as written in the design document, is a text file of messages. How do I set up Secor to do the same?

**Comment by jgagnon1** [comment]
`secor.file.reader.writer.factory=com.pinterest.secor.io.impl.DelimitedTextFileReaderWriterFactory` would be the one.

**Comment by anishmashankar** [comment]
thanks @jgagnon1.
