### ISSUE TITLE
http proxy support

### ISSUE THREAD

**Issue by vthakre** [pinterest/secor#173]
I am deploying secor on an EC2 instance and getting connection timeout error while putting data on S3. I found out that I need to set proxy.
When I set the proxy on command line such as
export http_proxy = xxxxxx

the aws s3 cp commands work.

Is there any configuration in secor that would allow me to set the proxy host and port

Thanks

**Comment by HenryCaiHaiying** [comment]
If you that environment variable, does secor upload work?

We don't need to deal with proxy here, the code don't deal with http
library directly.  It might just a few config property you need to set to
pass down to the AWS library, take a look at S3UploadManager and
HadoopS3UploadManager to see how to pass those properties.

**Comment by vthakre** [comment]
Thank you for your reply. I was able to modify the S3Uploader code to enable the support for proxy. Would it make sense to create a Pull Request.

Thanks

**Comment by HenryCaiHaiying** [comment]
Yes, please make a PR for your change to benefit other people as well.

**Comment by derekargueta** [comment]
@HenryCaiHaiying is this issue resolved? Looks like [this commit](https://github.com/pinterest/secor/commit/2401df69c17f49fb860613fb717c2d0733fa3a5e) is the fix, so perhaps this issue is good to close?

**Comment by vthakre** [comment]
Yes, this issue is resolved and can be closed @derekargueta
