### ISSUE TITLE
Add tags for releases?

### ISSUE THREAD

**Issue by jessitron** [pinterest/secor#180]
Would you mind adding tags to match the releases at http://mvnrepository.com/artifact/com.pinterest/secor ?

I'm pretty sure v0.15 is at f22e307cd8d1ada08d01f3f2432fdaded46cf329 (based on the logs for https://github.com/pinterest/secor/commit/3e3d25a4df9558e9441adc9a64a88db1eda6c899 ), but it'd be lovely to be sure.

**Comment by HenryCaiHaiying** [comment]
The tag for v0.15 was created right after f22e307:

    hcai@EX10914 secor (master)]$ git tag --contains f22e307

    v0.15

We usually created the tag right at the time we bump up the secor version
in pom.xml

**Comment by jessitron** [comment]
Are the tags not pushed to github? I don't see any tags in this repository at all.

![screen shot 2016-02-15 at 4 28 54 pm](https://cloud.githubusercontent.com/assets/1149737/13062029/47fc5612-d401-11e5-99a8-b1d8b86837ae.png)

**Comment by HenryCaiHaiying** [comment]
I just pushed v0.15 tag, can you use 'git tag' to verify?

**Comment by jessitron** [comment]
That worked! the v0.15 tag shows now. Thank you!

On Mon, Feb 15, 2016 at 6:43 PM, Henry Haiying Cai <notifications@github.com
