### ISSUE TITLE
How to set interval to consume data from Kafka

### ISSUE THREAD

**Issue by Bongsakorn** [pinterest/secor#181]
I wait for a long time. I checked lag offset via  progress monitor tool. I got 

[{"timestamp":1455767504,"tags":{"topic":"test_secor_twitter_2","partition":"0"},"metric":"secor.lag.offsets","value":"1000"},{"timestamp":1455767504,"tags":{"topic":"test_secor_twitter_2","partition":"0"},"metric":"secor.lag.seconds","value":"33263"}]

**Comment by HenryCaiHaiying** [comment]
What's the value of secor.max.file.age.seconds,
partitioner.finalizer.delay.seconds

Take a look at the secor log file and the data files on your machine
(pointed by secor.local.path) to see if you got any data files there.

**Comment by Bongsakorn** [comment]
I got it. Thank you very much for your quick response.
