### ISSUE TITLE
April 31st?

### ISSUE THREAD

**Issue by damaex17** [pinterest/secor#186]
We are inserting historical data and end up with strange upload folders in s3:

./secor.log.1:2016-03-09 08:52:50,091 [pool-1-thread-249] (org.apache.hadoop.fs.s3native.NativeS3FileSystem$NativeS3FsOutputStream:276) INFO  OutputStream for key 'GamePlayerDataEvents/dt=2015-04-31/hr=12/1_2_00000000000018209248.gz' closed. Now beginning upload

timestamp in message.timestamp.name field:
1429275228 
1429275368

**Comment by scravy** [comment]
@damaex17 which version of secor are you using? This sound like a typical concurrency issue and in an older version there were `static SimpleDateFormat` instances in the `TimestampedMessageParser`. In te current master branch those are no longer static with a comment about not being thread-safe ;-)

If these parsers are used across different threads this might not be enough, but I recommend upgrading secor and checking whether the problem still persists.

**Comment by damaex17** [comment]
Confirming the issue is fixed with the latest version.
