### ISSUE TITLE
ProgressMonitor fails in case of topic inactivity

### ISSUE THREAD

**Issue by hibikir** [pinterest/secor#189]
If a topic has been silent for the whole Kafka retention duration, Progress Monitor blows up completely, as it attempts to get an offset that is not available anymore, and responds with a plain Runtime Exception that is never caught:

```
java.lang.RuntimeException: Error fetching offset data. Reason: 1
    at com.pinterest.secor.common.KafkaClient.getMessage(KafkaClient.java:128)
    at com.pinterest.secor.common.KafkaClient.getCommittedMessage(KafkaClient.java:207)
    at com.pinterest.secor.tools.ProgressMonitor.getStats(ProgressMonitor.java:183)
    at com.pinterest.secor.tools.ProgressMonitor.exportStats(ProgressMonitor.java:131)
    at com.pinterest.secor.main.ProgressMonitorMain.main(ProgressMonitorMain.java:43)
```

At the very least, I think the exception should be caught, so that we still get information from other topics. My plan is to detect this specific error code, and then check if there are messages outstanding. If there aren't any, then our delay is zero (the topic is just very quiet). If there are some, our delay is the difference between the first and the last message, and throw a message into the log saying that it's possible that we have lost messages.

I'd love to hear if this is a sound plan, to hear if anyone has any better ideas, and to know if this enhancement is something you'd be interested in me PRing into the Pinterest repo.

**Comment by HenryCaiHaiying** [comment]
Agree we definitely should handle this exception.  If you want to fix
further, notice that even though the message is no longer in the broker,
but you have the two message offsets (last write message from the producer
and last read message from the consumer), if they are the same then no lag,
otherwise you might print the offset difference *
heuristic-of-per-message-gap.

**Comment by mcs1408** [comment]
Has there been any updates on this topic? I am currently having the same issue and would love to know how you fixed the problem.

**Comment by HenryCaiHaiying** [comment]
Not yet, you are welcome to make some code contributions along this line.

**Comment by mcs1408** [comment]
As stated beforehand the error is thrown when the ProgressMonitor tries to get a message from Kafka, but the topic is empty (e.g. due to ran out retention time). For my case I looked up the offsets of the wanted messages directly: the last committed message by Secor to S3 from Zookeeper and the last written message in the Kafka topic partition from Kafka using Secor's KafkaClient. If there is an offset lag calculated from those two values I try to get the specific message from Kafka and catch the mentioned error. If an error is thrown then I have an offset lag, but cannot retrieve the gap, if not I write the offset lag and proceed. This only fixes the issue for the actual offset lag. As the time lag in seconds is not needed for my case, I did not further investigate this direction. Below I pasted the changed getStats() method of the ProgressMonitor. In addition the findLastOffset() method of the KafkaClient had to be made public. Please give me feedback if this is useful for you and if I need to make improvements on the code.

`    private List<Stat> getStats() throws Exception {
        List<String> topics = mZookeeperConnector.getCommittedOffsetTopics();
        List<Stat> stats = Lists.newArrayList();

        for (String topic : topics) {
            if (topic.matches(mConfig.getMonitoringBlacklistTopics()) ||
                    !topic.matches(mConfig.getKafkaTopicFilter())) {
                LOG.info("skipping topic {}", topic);
                continue;
            }
            List<Integer> partitions = mZookeeperConnector.getCommittedOffsetPartitions(topic);
            for (Integer partition : partitions) {
                TopicPartition topicPartition = new TopicPartition(topic, partition);

                //1. get last offset committed to S3: from ZK
                long committedOffset = mZookeeperConnector.getCommittedOffsetCount(topicPartition);
                //2. get last written offset to Kafka: from Kafka
                SimpleConsumer consumer = null;
                long lastWrittenOffset = -1;
                try {
                    consumer = mKafkaClient.createConsumer(topicPartition);
                    lastWrittenOffset = mKafkaClient.findLastOffset(topicPartition, consumer) + 1;
                } finally {
                    if (consumer != null) {
                        consumer.close();
                    }
                }
                //3. compare
                long offsetLag = lastWrittenOffset - committedOffset;
                //3.1 if offset lag: check if topic empty
                if (offsetLag > 0) {
                    try {
                        Message committedMessage = mKafkaClient.getCommittedMessage(topicPartition);
                    } catch (Exception e) {
                        //3.1.1. if empty: log warning
                        if (e.toString().startsWith("java.lang.RuntimeException: Error fetching offset data. Reason: 1")) {
                            LOG.warn("Offset lag of {} in topic {}, partition {}, but missing messages not available in Kafka",
                                    offsetLag, topic, partition);
                        } else {
                            throw e;
                        }
                    }
                }
                //3.2 add offset lag to stats
                Map<String, String> tags = ImmutableMap.of(
                        Stat.STAT_KEYS.TOPIC.getName(), topic,
                        Stat.STAT_KEYS.PARTITION.getName(), Integer.toString(partition),
                        Stat.STAT_KEYS.GROUP.getName(), mConfig.getKafkaGroup()
                );

                long timestamp = System.currentTimeMillis() / 1000;
                stats.add(Stat.createInstance(metricName("lag.offsets"), tags, Long.toString(offsetLag), timestamp));

                LOG.debug("topic {} partition {} committed offset {} last offset {} committed timestamp {} last timestamp {}",
                        topic, partition, committedOffset, lastWrittenOffset);

            }
        }
        return stats;
    }

    private String metricName(String key) {
        return Joiner.on(".").join(mPrefix, key);
    }`

**Comment by HenryCaiHaiying** [comment]
Thanks for looking into this.  Several comments:

1. Your code seems a bit different than the code at head
2. If you just want to ignore the exception you got when
mKafkaClient.getCommittedMessage() is called (around line 183), it doesn't
seem you need to add that many code;
3. It would still be nice to get the seconds lag in that case, I think
kafka api give you both the last message and first message currently
available on broker side.  If you see committed offset is beyond that
range, you just need to make the call to retrieve the first message in the
broker.  Secor's ConsumerMain will actually moves to that firstMessage when
it realizes its previous committedMessage is out of service by broker;

**Comment by mcs1408** [comment]
1. The code is restructured a bit while I removed the parts that I did not need and added the additional offset lag handling.
2. I don't just want to ignore the message, I still want to log it, as some manual effort has to be taken if actual data loss has happened. Herein I made a small mistake, as currently I try to read the last committed message, which will still fail when it ran out of retention time, but new messages are now coming in. I switched to directly using the getMessage method from KafkaClient to increment the offset by one.
3. I do not plan on using the seconds lag anytime soon. Hopefully you can reuse parts of my code to fix the issue entirely.
