### ISSUE TITLE
Ignore parsing exceptions

### ISSUE THREAD

**Issue by jvaesteves** [pinterest/secor#1892]
Hello everyone, I want to configure a Secor instance to ignore a message if it would throw a exception (for example, if the timestamp column does not follow the expected input pattern, or if any other field does not match the expected schema), instead of just crashing the application. Does Secor have a property that allows this behavior? I have searched the properties files, but did not found anything similar to this.

**Comment by pdambrauskas** [comment]
I think it was fixed with https://github.com/pinterest/secor/pull/1547

You can configure how many bad records can be tolerated by setting `secor.consumer.max_bad_messages` property.

But this feature is not released yet, you should probably build from master.

**Comment by jvaesteves** [comment]
Thanks, this is working perfectly as intended.
