### ISSUE TITLE
Appending secor hostname to the S3 file name

### ISSUE THREAD

**Issue by vthakre** [pinterest/secor#191]
I want to consume data via secor from 3 Kafka Clusters and store the data on one bucket on S3.
I have secor hosts running for each Kafka Cluster.
Is there a way that I can add/append the hostname (of the secor instance) to the file (object) name ? 

Here is our setup.
Kafka Cluster deployed on 3 zones on AWS
Each cluster receives a different message
Secor needs to be setup on each zone to consume message from Kafka, but write messages from all 3 zones on to the same bucket (or path)

Currently I can create s3 path as 
S3://test_bucket/topic/zone1/secor_host1/1_000000000000
S3://test_bucket/topic/zone1/secor_host2/1_000000000000
S3://test_bucket/topic/zone1/secor_host2/1_000000000000
...
S3://test_bucket/topic/zone2/secor_host2/1_000000000000

How can I create files as 
S3://test_bucket/topic/zone1_secor_host1_1_000000000000
S3://test_bucket/topic/zone1_secor_host2_1_000000000000
S3://test_bucket/topic/zone2_secor_host1_1_000000000000
S3://test_bucket/topic/zone2_secor_host2_1_000000000000
...

Thanks

**Comment by HenryCaiHaiying** [comment]
The file path is controlled in MessageWriter.java as shown below.  The
IdUtil.getLocalMessageDir will get the concat of processId + threadId, if
you want hostname as part of the file path, you can potentially extend that.

mLocalPrefix = mConfig.getLocalPath() + '/' + IdUtil.getLocalMessageDir();
