### ISSUE TITLE
Expose JVM metrics when using Micrometer

### ISSUE THREAD

**Issue by DomWos** [pinterest/secor#1949]
Currently, only the custom metrics are exposed when using micrometer. Adding JVM internal metrics can be done in few lines of code and can greatly help when running secor on production.

**Comment by HenryCaiHaiying** [comment]
That sounds a good idea.  Will you be able to make a PR to make the
change?  It would be a great help for the community.

**Comment by DomWos** [comment]
Sure, will do it over the weekend :)

**Comment by HenryCaiHaiying** [comment]
Thanks
