### ISSUE TITLE
Add md5 hash to the prefix of s3 path for better partitioning of data

### ISSUE THREAD

**Issue by pritamm** [pinterest/secor#199]
S3 by default partitions the data based on the first directory inside the bucket. If that directory has same  or sequential ordered names then all that data is saved in a single partition. So if we add md5hash as the prefix in the S3 path the data gets partitioned evenly.

Adding the first 4 characters of md5 hash of the topic and the partitions, will help to better partition the data on s3.

**Comment by HenryCaiHaiying** [comment]
What will be the final output path look like?  s3://bucket/md5_1/topic1/...
 or s3://bucket/topic1/md5_1/...?   The first one might give you better
partitioning, but harder to traverse.

**Comment by pritamm** [comment]
It will look like the first one. Yes it will be harder to traverse, however helps for fast write and read access.
