### ISSUE TITLE
Scala 2.11 support

### ISSUE THREAD

**Issue by aloiscochard** [pinterest/secor#208]
Hi there,

Thanks for this great tool, we have started using it @BestMile but we are running on scala 2.11 and using  kafka 2.11.

Do you have plan to upgrade to kafka_2.11, or you prefer not for compatibility reason?

We are going to fork and try to the update yourself, please let us know what you think about that.

Cheers

**Comment by HenryCaiHaiying** [comment]
Do you embed secor in your application?

If you run secor standalone, I don't see the issue of scala 2.11 or 2.10,
secor is pure java code, it doesn't need any scala portion.  It will only
be a problem if you embed secor in your scala application or you modified
secor to call your scala code.

scala 2.10 or 2.11 is actually only an issue of kafka 8, when we move to
kafka 9 and using their new Consumer (which is pure java), scala version
would be even less an issue.

**Comment by tdroxler** [comment]
Yes we indeed embed secor in our application, we want to extends `MessageParser` such that we can extract the timestamp from our messages, which are in binary data.

**Comment by HenryCaiHaiying** [comment]
If the only extra code you added is to extract the timestamp, it doesn't
seem needs to be in scala.

But since secor is an open source project, you are pretty much open to do
what you want.  On our side, we don't have much resources on certifying
another version of language choice.

**Comment by tdroxler** [comment]
Hi,

FIY we updated to kafka 2.11 and it works well.

https://github.com/BestMile/secor/commit/9b1c9da3b57a46dae06688e3da0a1c42e05cffed

Thanks again for this great tools, can't wait to put it in prod,

cheers
