### ISSUE TITLE
Logger message

### ISSUE THREAD

**Issue by lovenishgoyal** [pinterest/secor#222]
Hi,

I am seeing all DEBUG messages while running secor. Below are my log4j config file.

### # log4j logging configuration.
log4j.rootLogger=CONSOLE, ROLLINGFILE
log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender
log4j.appender.CONSOLE.Threshold=WARN
log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout
log4j.appender.CONSOLE.layout.ConversionPattern=%d{ISO8601} [%t] (%C:%L) %-5p %m%n
log4j.appender.ROLLINGFILE=org.apache.log4j.RollingFileAppender
log4j.appender.ROLLINGFILE.Threshold=INFO
log4j.appender.ROLLINGFILE.File=/srv/www/secor_pipeline/current/logs/secor.log
log4j.appender.ROLLINGFILE.MaxFileSize=20MB
log4j.appender.ROLLINGFILE.MaxBackupIndex=50
log4j.appender.ROLLINGFILE.layout=org.apache.log4j.PatternLayout
log4j.appender.ROLLINGFILE.layout.ConversionPattern=%d{ISO8601} [%t] (%C:%L) %-5p %m%n

I am facing this issue with latest jar. Could you please let us know is there any issue with config file or we need to set any other property.

**Comment by HenryCaiHaiying** [comment]
Can you turn on log4j debug:

-Dlog4j.debug=true

**Comment by lovenishgoyal** [comment]
Hey Henry,
We don't want these debug messages on screen and log files. Looks like the property you mentioned is used for enabling debug msg.

**Comment by toddlers** [comment]
@HenryCaiHaiying ,

We have tried following as well

```
log4j.logger.com.pinterest.secor.writer.MessageWriter=INFO
log4j.logger.com.pinterest.secor.reader.MessageReader=INFO

```
in the log4 config file as well. But no luck. I found seems like something else as well

```
-log4j.appender.CONSOLE.Threshold=ERROR
+log4j.appender.CONSOLE.threshold=ERROR
```

From the log4j implementation I got this.

Plus the log4j version in the pom.xml is way too old . I am trying to upgrade the log4j to 1.2.17

**Comment by vikasr2011** [comment]
We are facing same issue, with latest release we are unable to different logger. We tried multiple loggers but only DEBUG logs are coming.

**Comment by HenryCaiHaiying** [comment]
Which java version are you using?  I am using java8 here, it seems fine for
me, I only see the INFO messages in the log.

When you turn on -Dlog4j.debug=true, does it show it was able to read your
log4j.properties file?

**Comment by toddlers** [comment]
@HenryCaiHaiying  We are using  java8 .

**Comment by toddlers** [comment]
@HenryCaiHaiying  if you can help us for this . That would be really great !

**Comment by HenryCaiHaiying** [comment]
It doesn't seem I am able to reproduce your problem.  Using
-Dlog4j.debug=true usually will tell something.  And check for the jars
having names include '*log*' to see whether there is a conflict there.

**Comment by lovenishgoyal** [comment]
Sure Henry,

We will also check from our side, Why we are facing this issue.



On Thu, Jun 23, 2016 at 4:39 AM, Henry Haiying Cai <notifications@github.com
> wrote:

> It doesn't seem I am able to reproduce your problem. Using
> -Dlog4j.debug=true usually will tell something. And check for the jars
> having names include '*log*' to see whether there is a conflict there.
>
> On Wed, Jun 22, 2016 at 5:37 AM, samtoddler <notifications@github.com>
> wrote:
>
> > @HenryCaiHaiying <https://github.com/HenryCaiHaiying> if you can help us
> > for this . That would be really great !
> >
> > —
> > You are receiving this because you were mentioned.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/pinterest/secor/issues/222#issuecomment-227729820>,
> > or mute the thread
> > <
> https://github.com/notifications/unsubscribe/AHCX_7hUjH8Ls-h7llSSCpONJcvF9bEnks5qOSyYgaJpZM4I2DdS
> >
> > .
>
> >
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pinterest/secor/issues/222#issuecomment-227904418>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AHcVM2Y2NHq2BUm_K2qCOVV_CgcQm4lyks5qOcDEgaJpZM4I2DdS>
> .
>



-- 
*Regards,*
Lovenish Goyal
*M: +91 9545461923** | Skype:  lovenishgoyal*

**Comment by toddlers** [comment]
Thanks @HenryCaiHaiying  ! 
We figured out the issue. 
Closing this now.

**Comment by lovenishgoyal** [comment]
We have one more dependency which have log4j jar. We resolved the issue. Thanks

**Comment by HenryCaiHaiying** [comment]
Good to know.
