### ISSUE TITLE
Google cloud storage credential file config should be optional

### ISSUE THREAD

**Issue by yunjing** [pinterest/secor#224]
`secor.gs.credentials.path` should be optional because if secor is running on Google Cloud VMs, no credential is needed. In fact, the code here https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/uploader/GsUploadManager.java#L114 already checks if the file config is null.

**Comment by HenryCaiHaiying** [comment]
Can you prepare a PR for this?

Thanks.

**Comment by yunjing** [comment]
https://github.com/pinterest/secor/pull/225
