### ISSUE TITLE
Update log4j library

### ISSUE THREAD

**Issue by liuweichu** [pinterest/secor#227]
Hello,

First, thanks for this great project. We are happily using it in our production to archive Kafka logs.

While we are trying to config the log4j layout with [EnhancedPatternLayout](https://logging.apache.org/log4j/1.2/apidocs/org/apache/log4j/EnhancedPatternLayout.html) , we found that secor is using a very old version of log4j - 1.2.15 which is released in 2007 and it doesn't support EnhancedPatternLayout.

So I want to know if there's a chance you can bump the version of log4j to 1.2.16+?

Thanks,
Liu

**Comment by HenryCaiHaiying** [comment]
We haven't got time to upgrade our log4j version, but we welcome the
community to do the experiment with the new log4j library.  If after
experimentation, you don't see any problems, please feel free to submit a
PR.

**Comment by liuweichu** [comment]
@HenryCaiHaiying 
Thanks for reply. Now we are simply replacing the lib to 1.2.17 and it is running well.
I will have it running on our server for a while, then make a PR.

**Comment by sundbry** [comment]
@liuweichu How has it been going? I am also interested in the 1.2.17 version for the EnhancedPatternLayout. I wouldn't expect any significant risk upgrading from 1.2.15.

**Comment by liuweichu** [comment]
@sundbry Hello, we are using 1.2.17 for half an year and causes no problems.

What we've done on our side is simply add the new .jar file and remove the old one.

Sorry I haven't make any PR for it's not high priority for us. If you don't bother, please feel free to make a PR. 😄
