### ISSUE TITLE
Kafka TCP connection leak

### ISSUE THREAD

**Issue by gubbin** [pinterest/secor#233]
Howdy.  We're having an issue where Secor steadily opens connections to Kafka brokers but does not close them.  Eventually, Secor will eat up all its FDs, unless it causes our Kafka brokers to fall over first.
For now, we just restart Secor daily.

**Comment by RainbowTraveller** [comment]
Hey did you find any work around or fix in terms of code change ? I am also observing res. memory increasing steadily unless one of the processes getting killed
