### ISSUE TITLE
can I make the secor to work across different kafka nodes?? if yes can you specify how?

### ISSUE THREAD

**Issue by praveen62** [pinterest/secor#239]

**Comment by HenryCaiHaiying** [comment]
Do you mean different kafka clusters?  We usually just set up different
secor nodes, one node (or process) for each kafka cluster.

**Comment by 62praveen** [comment]
thank you..  
can i set up 2-3 secor  processes for each topic?? and are these three secor processes can be coordinated with each other or they coordinate with zookeper?? 
thank you.

**Comment by HenryCaiHaiying** [comment]
Yes, you can setup multiple secor processes or threads to consume one
topic, but that also means you would need to partition that topic into
multiple kafka partitions.  One secor thread can consume one or multiple
kafka partitions, but not the other way around.

The co-ordination is done through ZK through kafka high level consumer.
