### ISSUE TITLE
Iso8601MessageParser does not create a correct logger instance for its class

### ISSUE THREAD

**Issue by agolotin** [pinterest/secor#243]
This is very minor, but if you look at [line 39 Iso8601MessageParser.java](https://github.com/pinterest/secor/blob/52a2a8b0e1bf6019177e24dc53d547464543043c/src/main/java/com/pinterest/secor/parser/Iso8601MessageParser.java#L39) it should be ```LoggerFactory.getLogger(Iso8601MessageParser.class)``` instead as far as I understand it...

**Comment by HenryCaiHaiying** [comment]
Good catch, would you like to submit a PR for the fix?

**Comment by KevinGrandon** [comment]
@HenryCaiHaiying Can this be closed now?

**Comment by HenryCaiHaiying** [comment]
This is fixed already.
