### ISSUE TITLE
protobufs

### ISSUE THREAD

**Issue by praveen62** [pinterest/secor#246]
For protobuf messages
I set secor.protobuf.message.class.*=<protobuf class name>
I placed proto.java file in place of <protobuf class name>  which was generated by executing the .proto file

But I am getting error : class not found exception 
Is there anything i need to do more about this 

Where should i keep the protobuf class ?? 
thank you

**Comment by HenryCaiHaiying** [comment]
We don't have a protobuf environment here, check with Michael spector, he
checked in most of the protobuf classes.

**Comment by dangoldin** [comment]
You need to have your protobuf files generated and placed into a jar that you can then include in the classpath. The other thing you'll need to keep in mind is that inner classes will need to be specified with a $ between the outer and inner class. Some examples below:

java -ea -Dsecor_group=dan_secor -Dlog4j.configuration=log4j.dev.properties -Dconfig=secor.prod.backup.properties -cp secor-0.22-SNAPSHOT.jar:lib/*:protobuf-files.jar com.pinterest.secor.main.ConsumerMain

secor.protobuf.message.class.topic_name=com.company.proto.OuterProtoClass$InnerProtoClass
