### ISSUE TITLE
Secor with zookeerper less Kafka

### ISSUE THREAD

**Issue by aashish-agarwal-de** [pinterest/secor#2478]
Does secor work with Kafka without a zookeeper?
According to this article: https://www.confluent.io/blog/kafka-without-zookeeper-a-sneak-peek/
There is a new Quorum controller, Kafka and Zookeeper are merged into one service

I tried providing `zookeeper.quorum` with the same hosts and kafka but no luck.

**Comment by saamarthgupta01** [comment]
Hey @aashish-agarwal-de 
Since this thread has been marked as closed, wondering if you found a solution to running Secor with the KRaft quorum controller?
