### ISSUE TITLE
kafka.offsets.storage=kafka not working

### ISSUE THREAD

**Issue by abstract-karshit** [pinterest/secor#249]
Error message:  (kafka.utils.Logging$class:68) INFO  Failed to fetch consumer metadata from broker:9092

**Comment by HenryCaiHaiying** [comment]
I am not sure whether secor supports kafka offset storage at this moment since we are writing offsets to ZK directly.

**Comment by abstract-karshit** [comment]
Currently we are using Kafka 10, any my client writes directly to kafka without the use of Zookeeper, I am simply unable to consume any message from this topic using Secor both with offset storage = zookeeper or offset storage = kafka. These properties are there in secor.common.properties.

**Comment by HenryCaiHaiying** [comment]
We haven't used kafka 10 here, I think there might be some other parameters
you need to set to make a kafka 8 client (secor) talks to kafka 10 broker
(e.g. downgrade the wire protocol from 10 to 8).

**Comment by kishorenc** [comment]
@abstract-karshit - We're running Secor again Kafka 10 without any issues. You've to configure Kafka to store offsets in ZK, and not Kafka.
