### ISSUE TITLE
local HDFS vs local FS

### ISSUE THREAD

**Issue by RainbowTraveller** [pinterest/secor#254]
This is not issue per say, but I need some expert opinion here.

HDFS and S3 have partition based storage mechanism, so will it be any convenient or faster to have local HDFS and write data there before uploading instead a local FS ?

**Comment by HenryCaiHaiying** [comment]
Are you using HadoopS3UploadManager or S3UploadManager.

In HadoopS3, we writes to a local file and using FileSystem's moveFromLocalFile: getFileSystem(dstCloudPath).moveFromLocalFile(srcPath, dstPath);

In S3UploadManager, we use S3's TransferManager:
        PutObjectRequest uploadRequest = new PutObjectRequest(s3Bucket, s3Key, localFile);
 
In both cases, the file was written local filesystem first.

**Comment by RainbowTraveller** [comment]
Well....I know what you are saying, but that does not answer my question, may be I did not ask my question properly, it is not about which upload manager to use for uploading the data to S3. 

Storing data locally is inevitable, it has to be done.

I was just asking, instead of local FS what if we use HDFS locally(say single node hadoop cluster). Will it give us any advantage as against using simple local file system ? Will it be faster because both HDFS and S3 store data as partition ? I hope that helps to clear my question.

**Comment by HenryCaiHaiying** [comment]
Why do you think the local HDFS would be faster than local filesystem?  HDFS would add more layer and overhead.

**Comment by RainbowTraveller** [comment]
I don't know the answer, that's why I am asking. I have not worked with hadoop or hdfs at all. I was just wondering if similarity in the storage mechanism in the form of partition if at all benefits transfer from local HDFS to S3. Looks like it is not good idea.

**Comment by HenryCaiHaiying** [comment]
I doubt you will get much benefit from using a local HDFS.  The local HDFS will for sure add overhead on top of the local filesystem.

For transferring to S3, it's almost always faster to use the S3's API (those Transfer Manager), then it doesn't really matter whether your local side is HDFS or not.
