### ISSUE TITLE
Record level compression/decompression 

### ISSUE THREAD

**Issue by lovenishgoyal** [pinterest/secor#255]
while reading from kafka we want to have gzip/custom decompression logic. Is this possible via "secor.compression.codec" property or we need to implement our own classes? If yes please let me know how can i implement same.

**Comment by HenryCaiHaiying** [comment]
Yes, you can use this property for compression, e.g. set it to '

org.apache.hadoop.io.compress.GzipCodec' or 'org.apache.hadoop.io.compress
.SnappyCodec'

**Comment by lovenishgoyal** [comment]
I tried this property but looks like this is for compression. We have
compressed msg coming via kafka and  we want to decompress these msgs and
store these to s3 with partition login on timestamp.

**Comment by HenryCaiHaiying** [comment]
You are right, those codecs are for file compression.

We have a MessageTransformer interface for people to transform the kafka message before writes out, maybe you can take a look to see whether you can use that to decompress the kafka message.

The other option is to take a look at the code in MessageReader, to see if you can specify a decompression option for ConsumerIterator to decompress the kafka message on the fly when the iterator iterates it.  But we have not using kafka message compression here, not sure whether it will work or not.
