### ISSUE TITLE
Support for Kafka 0.10

### ISSUE THREAD

**Issue by dangoldin** [pinterest/secor#258]
We recently upgraded our Kafka to 0.10 and decided to give Secor a shot. Everything's been great and we've been getting it to run but we're unfortunately running into a performance issue that's [highlighted](http://kafka.apache.org/0100/documentation.html#upgrade_10_performance_impact) in the Kafka 0.10 docs:

> The message format in 0.10.0 includes a new timestamp field and uses relative offsets for compressed messages. The on disk message format can be configured through log.message.format.version in the server.properties file. The default on-disk message format is 0.10.0. If a consumer client is on a version before 0.10.0.0, it only understands message formats before 0.10.0. In this case, the broker is able to convert messages from the 0.10.0 format to an earlier format before sending the response to the consumer on an older version. However, the broker can't use zero-copy transfer in this case. Reports from the Kafka community on the performance impact have shown CPU utilization going from 20% before to 100% after an upgrade, which forced an immediate upgrade of all clients to bring performance back to normal. To avoid such message conversion before consumers are upgraded to 0.10.0.0, one can set log.message.format.version to 0.8.2 or 0.9.0 when upgrading the broker to 0.10.0.0. This way, the broker can still use zero-copy transfer to send the data to the old consumers. Once consumers are upgraded, one can change the message format to 0.10.0 on the broker and enjoy the new message format that includes new timestamp and improved compression. The conversion is supported to ensure compatibility and can be useful to support a few apps that have not updated to newer clients yet, but is impractical to support all consumer traffic on even an overprovisioned cluster. Therefore it is critical to avoid the message conversion as much as possible when brokers have been upgraded but the majority of clients have not.

Changing the dependency in pom.xml and fixing a broken call in a test ( /test/java/com/pinterest/secor/performance/PerformanceTest.java) I was able to get the code to build.

Do you think it's worthwhile to officially support 0.10 and do you have any concerns with me working on a PR? I don't know what kind of performance/backwards compatibility you'd expect.

**Comment by dangoldin** [comment]
Forgot to mention that the upgrade also marks a variety of calls deprecated so glad to take care of those as well.

**Comment by HenryCaiHaiying** [comment]
Thanks for looking into kafka 10 since we are also in the middle of migration.  For that performance problem, was the fix just to set the broker message format to 0.8?

On the changes you need to make for secor, do you need to modify some APIs to make it not backward compatible?  We still have quite many customers on kafka 8

**Comment by dangoldin** [comment]
Yea - the fix is to change the broker message protocol to 0.8 but in our case it was a brand new Kafka 0.10 cluster that we've been running with 0.10 messages so it was easier for us to upgrade the Kafka client in Secor to be 0.10 compliant.

The only breaking change was in a test with a pretty minimal diff. There were also a lot of calls that the new Kafka client marks as deprecated but as far as I can tell the code's running fine. We're actually running it in pre production now and haven't seen any issues.

**Comment by HenryCaiHaiying** [comment]
Will the change in that test be made to work in both kafka 8 and kafka 10 env?

If it's not too much work for you, we would like to take in that PR to make secor work for kafka 10.

**Comment by dangoldin** [comment]
Cool - I'll try to get something together this week.

**Comment by doriwal** [comment]
Hi 

I just added in my copy of secor support to kafka 10 

the changes are : 

1) in pom.xml change to 

<dependency>
            <groupId>org.apache.kafka</groupId>
            <artifactId>kafka_2.10</artifactId>
            <version>**0.10.0.0**</version>
            <exclusions>
                <exclusion>
                    <groupId>org.slf4j</groupId>
                    <artifactId>slf4j-simple</artifactId>
                </exclusion>
            </exclusions>
        </dependency>


2) in PerformanceTest.java

**import kafka.admin.RackAwareMode;
import kafka.utils.ZkUtils;
import org.I0Itec.zkclient.ZkConnection;**

private static void createTopics(List<String> topics, int partitions, String zkConfig) throws InterruptedException {

        ZkClient zkClient = createZkClient(zkConfig);
        **ZkUtils zkUtils = new ZkUtils(zkClient, new ZkConnection(zkConfig),false);**
        try {
            Properties props = new Properties();
            int replicationFactor = 1;
            for (String topic : topics) {
                AdminUtils.createTopic(**zkUtils**, topic, partitions, replicationFactor, props, **RackAwareMode.Enforced$.MODULE$**);
            }
        } catch (TopicExistsException e) {
            System.out.println(e.getMessage());
        } finally {
            zkClient.close();
        }

    }

3) and just to be in the safe side I also added in MessageReader.java in createConsumerConfig() 
 **props.put("bootstrap.servers",mConfig.getKafkaSeedBrokerHost());**


4) The only thing that I dont understand is that i tried to change from default "smallest" to "earliest"
        props.put("auto.offset.reset", "earliest");

and It didnt worked , I return it to "smallest" and it is working

**Comment by dangoldin** [comment]
There's an open PR that works and it does basically what @doriwal suggested. Kafka 0.10 introduced a breaking API change for topic creation so I just have to figure out how to support both versions in the unit test.

Changing the pom.xml to 0.10 will get it to build and run but will break the test.

**Comment by HenryCaiHaiying** [comment]
If the problem is just on PerformanceTest.java, I think we can comment it
out (leaving comments on how to enable it for both k8 and k10), it doesn't
seem PerformanceTest was used internally here or in the unit test.

**Comment by dangoldin** [comment]
Ah got it. Let me update the test then and that should be it.

**Comment by dangoldin** [comment]
Updated the PR to support both versions of the Kafka client (0.8 and 0.10) using a separate build profile.

**Comment by fredriv** [comment]
Hi! We're looking at using Secor against our 0.10.2 Kafka brokers. I see that Secor is using the old consumer client with offsets in Zookeeper, even if built with the 0.10 libraries.

What are your experiences using this against 0.10.x brokers? I assume you avoid the performance issues noted in the upgrade docs? Are there any issues with partition offsets when restarting Secor etc? Is there any specific broker or Secor config we should be aware of?

**Comment by dangoldin** [comment]
Yea - we initially tried using the Secor library using the 0.8 clients against the 0.10 brokers and ended up running into the above performance issues. Upgrading the client libraries solved our performance issues and was a minimal code change since it was just importing a different Kafka client version.

We didn't have to change the configs for this since we still use ZooKeeper to store the offsets. We didn't reuse the same named consumer group after making the change to the 0.10 client though so can't tell whether that would cause any issues.

**Comment by Fluxx** [comment]
Hey Everyone,

Thanks for the diligence and explanations on all of this. We're in the process of an upgrade as well, and wanted to verify things. Our current setup is this:

* Running brokers at version `0.10.2.1`
* Have `log.message.format.version=0.8.2 ` currently
* Have upgraded secor to a version that support `0.10`
* Have migrated offset tracking from zookeeper to kafka with secor

Assuming the above is all true, I just wanted to confirm that we can set `log.message.format.version=0.10.2` and secor will be be using the new message protocol? I believe this to be true, even though secor is using the deprecated `ConsumerConnector` API for communicating with Kafka, but just wanted to double check.

**Comment by dangoldin** [comment]
Do you have a sand environment you can test this in? It's very order dependent and may cause some problems unless you're careful.

I think to be safe you may want to rebuild secor with the explicit 0.10 support and then run it as a under a separate consumer group to make sure it's working as expected. Then when you're confident switch your application over to use this new secor deployment.

**Comment by Fluxx** [comment]
We did have a test secor environment where we tested the upgrade. We've actually already upgraded our brokers to 0.10.2.1, with `log.message.format.version=0.8.2`, and deployed an upgraded secor deployment which uses 0.10 kafka.

Our main question was mostly about going to `log.message.format.version=0.10` and if the secor consumer will be able to understand the new 0.10 kafka message format. My understanding is that the consumer connector API vs the new consumer API is purely a consumption choice, and on-disk message format for a broker is independent. i.e. the old consumer connector consumer can consume 0.10 format messages.

We're mostly just trying to be cautious with changing the `log.message.format.version` value, as the secor consumer is our largest consumer of this cluster, and as such if upgrading the `log.message.format.version` causes a CPU overloaded cluster, we'd have to scramble to upgrade our brokers. Something we'd obviously not do.

**Comment by HenryCaiHaiying** [comment]
I think that message format change is mostly about the new timestamp field in the message header, and it will work with the secor with 0.10.2.1 build profile.  I think there are other customers who already used the new message format, they already modified secor API to extract the timestamp field in the message header.

**Comment by Fluxx** [comment]
Ah Excellent, that's great to hear! Thanks again for all the hard work.
