### ISSUE TITLE
write parquet 

### ISSUE THREAD

**Issue by doriwal** [pinterest/secor#263]
Can I use secor to read data from kafka and save it in s3 in parquet format  ? How ?

If the answer is Yes , Can the data that I am reading from kafka be in json format  ?

**Comment by HenryCaiHaiying** [comment]
It's possible, but you need to write either thrift->parquet or
protobuf->parquet converter.  I think someone already contributed
protobuf->parquet.

From json->parquet, you probably would need to use the json->avro->parquet
through the kite sdk,
http://kitesdk.org/docs/1.1.0/Parquet-vs-Avro-Format.html

We have the code to do those in our nextgen ingestion framework: merced,
but we haven't got the time to open source it.

**Comment by arvind-kalyan** [comment]
Hi Henry, 
Can you let me know if the json->parquet has been solved for? We're encountering a similar use case. Can we do something to open-source atleast the parser if it has already been written as a part of `merced` like you mentioned above?  

Thanks!

**Comment by HenryCaiHaiying** [comment]
Yes, we have implemented the json->avro->parquet converter in merced, and
it was based on kite sdk.  But I don't think it would be easy to open
source that part of the code.

**Comment by doriwal** [comment]
Hi 

I am having problems to add the Kite logic to secor 

I founded this code [https://stackoverflow.com/questions/39858856/json-object-to-parquet-format-using-java-without-converting-to-avrowithout-usin] - 

Is it possible to put a snippet how to do it ? some basic example could help

**Comment by HenryCaiHaiying** [comment]
Did that JsonUtils.inferSchema thing work for you?  I did have an avro
schema for my json.

**Comment by richardxin** [comment]
Henry, 
we have the same requirement to read kafka message in json format to save as parquet on S3, any good example on how to do it? i.e. a "hello world" example?

**Comment by manthanBhayani** [comment]
> Henry,
> we have the same requirement to read kafka message in json format to save as parquet on S3, any good example on how to do it? i.e. a "hello world" example to read kafka message in json format to save as parquet on S3?

Did you find any good example of above requirement or if you have written please share the example. we are also stuck with writing to s3 from kafka via Secor.
