### ISSUE TITLE
Customize upload logic secor.max.file.age

### ISSUE THREAD

**Issue by morrifeldman** [pinterest/secor#266]
Currently secor uploads files when the file age of the newest file per topic and per partition exceeds secor.max.file.age.

For our use case it would be better to upload when the age of the oldest file exceeds secor.max.file.age.

Pull requst #265 adds a configuration parameter to switch to uploads based on oldest file age.

Please let me know what you think.

Here are some relevant discussions on the mailing list:

https://groups.google.com/forum/#!msg/secor-users/wxO0Eb83_R4/3VW8VHrwWzEJ
https://groups.google.com/forum/#!topic/secor-users/HStU5erKP70

**Comment by msperlich** [comment]
This is great, thanks!
