### ISSUE TITLE
Reusable classes, members acceptability is private while it should be protected

### ISSUE THREAD

**Issue by doronl** [pinterest/secor#287]
Hi,

  It is nice you give option to override classes via configuration but you need to go one more step...
 
  In classes like TimestampedMessageParser, HadoopS3UploadManager, Uploader and Consumer almost all fields and some methods are private... if you want to inherit to change one functionality you are forced to copy code and\or do ugly stuff... can you can change this?

Thanks,
 Doron

**Comment by HenryCaiHaiying** [comment]
Good observation.  When those classes were first designed, we didn't think much about extension.  If you do see the need to inherit and then override, feel free to change some fields/methods from private to protected.

**Comment by doronl** [comment]
Thanks, OK, I made few changes, please see if they are OK

Regards,
 Doron
