### ISSUE TITLE
Few questions

### ISSUE THREAD

**Issue by simplesteph** [pinterest/secor#296]
Hi,

Not sure if the right place, but:
 - what would be the difference of secor vs a Kafka Connect to S3?
 - can secor be used to recover a kafka cluster in case of disaster? Meaning rebuilding a Kafka Cluster entirely from a secor backup

Thanks,
Stephane

**Comment by HenryCaiHaiying** [comment]
- secor vs. kafka connect, secor is more lightweight and yet still provides capability to parse the message in different format: Thrift/JSON and generate output in compressed/uncompressed, SequenceFile/Parquet format;
- For restoring, there is a OffsetMessageParser in secor which keep the kafka messages in its original format for restoring purpose.

**Comment by simplesteph** [comment]
Hi @HenryCaiHaiying thanks a lot for your answer. Regarding the restoring, is there something that exists out there that demonstrates how to restore messages using the OffsetMessageParser?

Also, is there something like a consumer that would consume Kafka data from S3, or do we have to create our own?

**Comment by HenryCaiHaiying** [comment]
There is no ready-made restore tool, but you can write a tool to publish
back those messages back to kafka since the messages are saved in the exact
offset order corresponding to their kafka position.

The consumer is already included in secor code, there is no need to create
another one.

**Comment by simplesteph** [comment]
Thanks! By consumer, I meant consumer that reads from S3, not the Secor Consumer that reads from Kafka. Basically the use case is that someone can "replay" data using a special consumer directly from S3. Is there such thing?

**Comment by HenryCaiHaiying** [comment]
We don't have ready-to-made code for that, but I don't think it will be
hard to write some code to read the file from S3 and then publish the
record back to Kafka.

**Comment by simplesteph** [comment]
Thanks!

Finally, are there plans to support the timeindex of kafka 0.10.1.0 soon? I don't believe those would be lost with the current OffsetMessageParser class?

**Comment by HenryCaiHaiying** [comment]
For timeindex, do you mean rewind to a particular offset point
corresponding to a timestamp?  It might be just easier to write a separate
tool to rewind the secor consumer's offset point to those points.  The
capability of getting the offset point for a particular time existed in
kafka 8 as well, it's just not as accurate, it can rewind to an offset
which is a little before the time you gave.

**Comment by simplesteph** [comment]
I mean backing up the timeindex that Kafka 0.10.1 writes (it's a new feature of kafka). See `offsetsForTimes` here: https://kafka.apache.org/0101/javadoc/index.html?org/apache/kafka/clients/consumer/KafkaConsumer.html

**Comment by ashvini** [comment]
Hi,
Do you have code snippet to implement kafka messages recovery using secor 

Regards,
ashwini
