### ISSUE TITLE
Build fails : Could not find artifact com.twitter:scro oge:jar:2.5.4

### ISSUE THREAD

**Issue by vermasunil21** [pinterest/secor#297]
`[ERROR] Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project secor: Execution thrift-sources of goal com.twitter:maven-finagle-
thrift-plugin:0.0.9:compile failed: Plugin com.twitter:maven-finagle-thrift-plugin:0.0.9 or one of its dependencies could not be resolved: Could not find artifact com.twitter:scro
oge:jar:2.5.4
`

**Comment by dangoldin** [comment]
What build command are you executing?
