### ISSUE TITLE
Release cycle for 0.10 support

### ISSUE THREAD

**Issue by witZack** [pinterest/secor#317]
Currently we're looking at releasing kafka 0.10 everywhere and want to leverage the protocol, but don't want to just adhoc grab master / run the dev profile for 0.10.

Is there an expected release cycle for 0.10 support?

**Comment by HenryCaiHaiying** [comment]
I see your point.  So far all the versions we cut for secor are based on people's request.  Each version cut actually has nothing to do with kafka version, from the source code of secor, it's the same.  You can always do a local build of secor with kafka 10 profile to rebuild it with kafka 10 library after you pulled a particular version of secor from maven central.

But this might raise the issue on whether we should just switch the default build/profile of secor using kafka 10 libraries.
