### ISSUE TITLE
Java 7 Failing Tests

### ISSUE THREAD

**Issue by IvanAtanasov** [pinterest/secor#318]
When trying to build Secor using java 7 (OpenJDK 1.7.0_95) there are 2 failing tests.

>   SplitByFieldMessageParserTest.testExtractHourlyPartitionsForNonUTCTimezone:155 expected:<hr=0[8]> but was:<hr=0[2]>
>   JsonMessageParserTest.testExtractHourlyPartitionsForNonUTCTimezone:178 expected:<hr=0[8]> but was:<hr=0[2]>

Both involve using a none UTC timezone. Maybe the way the timezone is specified does not work as expected in java versions prior to 8?

I'm using java 8 now anyway but thought I'd point this out, as there is no mention anywhere of the project only supporting java 8.

**Comment by HenryCaiHaiying** [comment]
We have a travis build running on Oracle JDK7 which is fine.

I guess the problem is either because the difference between Oracle JDK7
and OpenJDK7, or when the test was not running from US timezone.

I haven't got time looking into this, but you know how to fix the test,
that would be great.
