### ISSUE TITLE
ORC support required

### ISSUE THREAD

**Issue by ashubhumca** [pinterest/secor#326]
Hi, Do we have any plan to support ORC format? This is important for HIVE tables which work best with ORC.

**Comment by HenryCaiHaiying** [comment]
No immediate plan.  You are welcome to make the contribution to enable that feature.  People in the community already enabled Parquet support.

**Comment by jaimess** [comment]
In my fork you can find an avro to writer, have a look.

**Comment by ashubhumca** [comment]
I'll work on this feature.

**Comment by HenryCaiHaiying** [comment]
Thanks @ashubhumca

**Comment by ashubhumca** [comment]
Functionality added
