### ISSUE TITLE
Memory Footprint of Parquet Writers

### ISSUE THREAD

**Issue by thegeebe** [pinterest/secor#328]
I'm getting `java.lang.OutOfMemoryError: Java heap space` errors when using the `ProtobufParquetFileReaderWriter`. I know a simple solution is usually to increase memory size, but the amount of data coming through wouldn't warrant it.

Some stats:
- Running as a StatefulSet on Kubernetes on AWS
- Kafka 0.10
- 120 Partitions in Kafka input topic. The Kafka partitions are hashed on the same keys that I want to partition my Secor output with, to ensure that no two threads need to write to the same s3 dir/minimize the number of local files each thread is required to write to.
- 5 Secor processes and 7 consumer threads.
- Each process runs in a docker container with 2.5G memory
- Each process has the java heap specified as 2G
- Each process gets 250m cpu
- Input data is Protobuf

This configuration is perfectly stable when using something simple like the `OffsetMessageParser` or even `ProtobufMessageParser`. However, when rolling my own parser that uses a field whose values are uniformly distributed across 577 unique integers, I very quickly run out of memory. The size of my input data is probably < 10MB at the time the consumers begin to fail. If I increase the amount of CPU allocated to each process, it fails faster, presumably because it is able to process more events.

I don't think this is a protobuf issue, because other parsers/output groupers work fine. My initial reaction was that this could be the overhead of having 577 parquet writers, and that converting to parquet is more memory intensive than, say, a sequence file. However, each thread should only have a handful of writers if Secor is distributing the load the way I think it should be, considering how my topics are partitioned.

Currently I'm trying to connect a remote debugger to analyze the heap, but was wondering if you had any tips/insights into the memory overhead of the parquet writer.

---
This is my parser, which I don't believe is responsible for any sort of bad memory mangement:
```java
public class EventParser extends MessageParser {

	private static final Logger LOG = LoggerFactory.getLogger(EventParser.class);

	private EventConfig eventConfig;
	private ProtobufUtil protobufUtil;

	public EventParser(SecorConfig config) {
		super(config);

		eventConfig = new EventConfig(config);
		protobufUtil = new ProtobufUtil(config);
	}

	@Override
	public String[] extractPartitions(Message message) throws Exception {
		com.google.protobuf.Message decodedMessage = protobufUtil.decodeMessage(message.getTopic(), message.getPayload());

		String event_date = "event_date=" + decodedMessage.getField(decodedMessage.getDescriptorForType().findFieldByName("event_date")).toString();
		String s2 = "s2_cell_level_6=" + decodedMessage.getField(decodedMessage.getDescriptorForType().findFieldByName("s2_cell_level_6")).toString(); //Long.toString(event.getS2CellLevel6());
		String source_date = "source_date=" + decodedMessage.getField(decodedMessage.getDescriptorForType().findFieldByName("source_date")).toString(); //event.getSourceDate();

		return new String[]{event_date, s2, source_date};
	}
}

```

**Comment by HenryCaiHaiying** [comment]
Parquet conversion takes lots of memory especially when your schema has many columns.  Even when most of the columns are NULL, parquet still needs to convert each column value.  If you can drop some columns out of protobuf/parquet schema, that will help.

**Comment by thegeebe** [comment]
The schema is pretty bare, and it seems strange to me that the memory is actually being consumed from the conversion since the input data is only about 10 Megs (over the 5 processes) before one of them starts to fail. I read about Parquet writers, and it seems like the writer must allocate a buffer the size of the parquet row group/block size (defaults to 128MB) for each file that is being written to, regardless of any schema details. From this, the following consideration come to mind:

- As Kafka partitions are reblanced/new Secor processes join the group/consumer threads otherwise relinquish their claims on Kafka partitions, how does Secor handle writers that would no longer be needed?

**Comment by HenryCaiHaiying** [comment]
The writer class has a close method, I think secor will call this method to
close the writer.  Maybe you can take a look to see whether parquet's
memory is released when ProtobufParquetReaderWriter's close is called.

**Comment by thegeebe** [comment]
Here are my findings:
- Parquet's writing buffers are indeed released and can be collected after the writer is closed and removed from the `FileRegistry`
- My memory errors were coming from bad Kafka partitioning and dictionary encoding.

In Secor, dictionary encoding is enabled by default and cannot be turned off. In Parquet 1.8, each column chunk writer with dictionary encoding enabled immediately allocates a buffer that is the default dictionary page size (I believe 64K `int`s so 256KB). This, coupled with my bad kafka partitioning that lead to many secor threads writing to the same output partition, blew up the memory.

In Parquet 1.9 (change [here](https://issues.apache.org/jira/browse/PARQUET-585)), the dictionary page buffer is initialized with 4K integers first, and then grown as needed to accommodate the current column. This greatly improved my memory performance.

Currently, there is no way to alter the default row group size (`parquet.block.size`), page size (`parquet.page.size`), dictionary behavior, or validation behavior. While the column chunk and row group buffers don't seem to be allocated all at once, over time they would have lead to a memory failure.

I made these options configurable, reduced the block and page sizes, bumped the parquet version to 1.9, and, for my use case, turned off dictionary encoding and memory was much more reasonable. I believe these options should be open to the user, and can submit a PR that makes them accessible if you agree, though am not sure if you'd want to switch to 1.9.

**Comment by HenryCaiHaiying** [comment]
Gabe,

Those are very good findings.  Can you prepare a PR to submit the changes
you made?

Thanks.
