### ISSUE TITLE
Support for kafka's message built-in timestamp 

### ISSUE THREAD

**Issue by igorcalabria** [pinterest/secor#330]
Hi,
Since version `0.10.0.0` kafka's messages includes a timestamp metadata field [0]. It seems logical to include a `MessageParser` for this. We already have a working version and I could create a PR if there's interest.  

[0] https://issues.apache.org/jira/browse/KAFKA-2511

**Comment by HenryCaiHaiying** [comment]
That does sound a good suggestion.  Can you prepare a PR if you already
have a working version?

**Comment by tygrash** [comment]
I would like to raise a PR for the same. Please add me to the contributer list. I am not able to push anything

```remote: Permission to pinterest/secor.git denied to tygrash.
fatal: unable to access 'https://github.com/pinterest/secor.git/': The requested URL returned error: 403```

**Comment by HenryCaiHaiying** [comment]
Is this failure from 'git push' command?

**Comment by tygrash** [comment]
Yes. I checked out a branch in my local and trying to push it by `git push --set-upstream origin branch_name` command, then getting this error

**Comment by tygrash** [comment]
Found the issue. I didn't fork any branch :P 

https://github.com/pinterest/secor/pull/336 please review

**Comment by igorcalabria** [comment]
I'll close this issue since @tygrash implemented this feature. 

Great work!
