### ISSUE TITLE
Zookeeper requirements in README

### ISSUE THREAD

**Issue by dmowcomber** [pinterest/secor#332]
When running docker I get a zookeeper error but zookeeper is not listed in the readme at all.

`ZOOKEEPER_QUORUM variable not set, launch with -e ZOOKEEPER_QUORUM=zookeeper:2181`

**Comment by HenryCaiHaiying** [comment]
I am not familiar with docker setup, is your zookeeper hosts actually called 'zookeeper'?  You are supposed to put in the host name for ZK there.

**Comment by enisher** [comment]
@dmowcomber `ZOOKEEPER_QUORUM` is a required parameter for docker to correctly initialize `zookeeper.quorum` in the secor config.

**Comment by dmowcomber** [comment]
Thanks for the clarification.
