### ISSUE TITLE
Secor crashes with NPE

### ISSUE THREAD

**Issue by dovka** [pinterest/secor#339]
Updated to 0.23 once it was released and now secor crashing immediately after start with NPE
(see logs below)

My previous version compiled with change 1fbad266cd955348fdb9a66d24a1d057038c5e9f works fine.

2017-05-18 12:02:21,446 [Thread-3] (com.pinterest.secor.main.ConsumerMain$1:65) ERROR Thread Thread[Thread-3,5,main] failed
java.lang.RuntimeException: Failed to initialize the consumer
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:90)
Caused by: java.lang.NullPointerException
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:191)
        at com.pinterest.secor.util.ReflectionUtil.createMetricCollector(ReflectionUtil.java:218)
        at com.pinterest.secor.consumer.Consumer.init(Consumer.java:70)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:88)

See the complete log:
[secor_npe.txt](https://github.com/pinterest/secor/files/1010775/secor_npe.txt)

**Comment by tygrash** [comment]
try adding `secor.monitoring.metrics.collector.class=com.pinterest.secor.monitoring.OstrichMetricCollector` in properties file.

**Comment by dovka** [comment]
Thank you, that works.
My config files were created a few months ago and I never added that new setting there.

Would be nice to handle the NPE in case classname config setting is missing.

**Comment by tygrash** [comment]
@HenryCaiHaiying do wo need to add this config in common.properties?

**Comment by HenryCaiHaiying** [comment]
This property is present in secor.common.properties.  If you maintain your
own copy of properties, you would need to add this property if you sync to
head on secor github:

# Class that manages metric collection.

# Sending metrics to Ostrich is the default implementation.

secor.monitoring.metrics.collector.class=com.pinterest.secor.monitoring.OstrichMetricCollector

**Comment by tygrash** [comment]
Yes, its present. Thanks for clarification.

**Comment by dovka** [comment]
Is it possible then to have the code return intelligent message about secor.monitoring.metrics.collector.class missing instead of the NPE?
It can gracefully exit with that message.

**Comment by HenryCaiHaiying** [comment]
I think you can add a check in ReflectionUtil.java to check whether the
clasname is null, do you have time to make a contribution to do that fix?
Wouldn't take too much time.

**Comment by tygrash** [comment]
I guess we should make change in SecorConfig.java and call ` return getString("secor.monitoring.metrics.collector.class");` instead of `return mProperties.getString("secor.monitoring.metrics.collector.class");
` as getString has a check for presence of class in mProperties.

Raised PR https://github.com/pinterest/secor/pull/340

**Comment by HenryCaiHaiying** [comment]
Looks good to me.

**Comment by tygrash** [comment]
@dovka can you close this issue? PR is already merged for this.

**Comment by dovka** [comment]
Good job guys :)

**Comment by HenryCaiHaiying** [comment]
Thanks @tygrash
