### ISSUE TITLE
Backing up Kafka messages timestamp

### ISSUE THREAD

**Issue by nachomdo** [pinterest/secor#342]
Hi, 
As you are probably aware, Kafka 0.10 message format includes a timestamp field. I wonder if you are thinking about providing some mechanism to back up this field as well. At the moment, only Offset, Key and Payload fields are saved. 

I have made some changes for MessagePackSequenceFileReader and Writer in my fork to support this so, I could open a PR if this is something you want to have as part of Secor. 

Thanks 😃

**Comment by HenryCaiHaiying** [comment]
In https://github.com/pinterest/secor/commit/cff776388fc497d4193d910feb182eeffeab74ab, tygrash added the capability of using the timestamp field from kafka 10 message.

How do you use the the timestamp in your fork?

**Comment by nachomdo** [comment]
Thanks for replying so quickly. Maybe I'm missing something. What I want to do is backup messages from one environment including the timestamp and restoring them in other environment using a Kafka Client 0.10 that allows to specify the timestamp of a given message. 

The tool I have to restore messages is using a reader created with `MessagePackSequenceFileReaderWriterFactory` to read the files produced by Secor. The reader allows us to iterate over a collection of `KeyValue` which contain the fields: offset, key, value. I have noticed that, at least in the MessagePackSequenceWriter, the offset is encoded as part of the key. I have just leveraged the fact that `ParsedMessage` contains already the timestamp field, added a timestamp field to `KeyValue` and changed how the message is encoded and decoded using MessagePack to consider the new timestamp field as well. 

```java
        @Override
        public void write(KeyValue keyValue) throws IOException {
            byte[] kafkaKey = keyValue.getKafkaKey();
            // output size estimate
            // 1 - map header
            // 1 - message pack key
            // 9 - max kafka offset
            // 1 - message pack key
            // 9 - kafka timestamp
            // 1 - message pack key
            // 5 - max (sane) kafka key size
            // N - size of kafka key
            // = 26 + N
            ByteArrayOutputStream out = new ByteArrayOutputStream(26 + kafkaKey.length);
            MessagePacker packer = MessagePack.newDefaultPacker(out)
                    .packMapHeader((kafkaKey.length == 0) ? 2 : 3)
                    .packInt(KAFKA_MESSAGE_OFFSET)
                    .packLong(keyValue.getOffset())
                    .packInt(KAFKA_MESSAGE_TIMESTAMP)
                    .packLong(keyValue.getTimestamp());
            if (kafkaKey.length != 0) {
                packer.packInt(KAFKA_HASH_KEY)
                        .packBinaryHeader(kafkaKey.length)
                        .writePayload(kafkaKey);
            }
            packer.close();
            byte[] outBytes = out.toByteArray();
            this.mKey.set(outBytes, 0, outBytes.length);
            this.mValue.set(keyValue.getValue(), 0, keyValue.getValue().length);
            this.mWriter.append(this.mKey, this.mValue);
        }
```
When I saw tygrash's changes I couldn't find where the timestamp was being encoded and stored with the message. I thought that was just a way to group messages in S3 by timestamp. 

Thanks

**Comment by HenryCaiHaiying** [comment]
We didn't use MessagePack here, so my knowledge might be limited.
 tygraph's change is basically using the timestamp in k10's meta fields if
it is present, (previously most people are specifying a timestamp field
inside the message).  It is for time-bucket the sequence file, that's
actually how most people using secor for.

If you want to add timstamp field inside KeyValue class, I am fine with
that, but make sure you take care of the case that timestamp field is
optional in k10.  And if you want, you can also try to handle the cases
where timestamp is specified inside the message body (you can look at
TimestampedMessageParser).


On Thu, Jun 8, 2017 at 11:27 AM, Nacho Muñoz Gómez <notifications@github.com
