### ISSUE TITLE
ProtobufORCFileReaderWriter

### ISSUE THREAD

**Issue by andredasilvapinto** [pinterest/secor#343]
It would be nice to have a Protobuf to ORC converter, like there is a Protobuf to Parquet converter.

**Comment by HenryCaiHaiying** [comment]
We are not familiar with ORC format, but certainly welcome the community contribution.

**Comment by deepak-batra** [comment]
I've already worked on this based on secor-0.21 and we've been using this in production. Would like to contribute to the secor-community.

**Comment by HenryCaiHaiying** [comment]
@deepak-batra Feel free to make a PR for your work, we welcome the community contribution.

**Comment by deepak-batra** [comment]
sure @HenryCaiHaiying, will be raising a PR in a few days.

**Comment by deepak-batra** [comment]
Hey, @HenryCaiHaiying is there a documentation to raise a PR .. ?

**Comment by HenryCaiHaiying** [comment]
This would be standard github PR process: https://help.github.com/articles/about-pull-requests/

**Comment by deepak-batra** [comment]
Hey @HenryCaiHaiying, I've raised a PR for the same.

**Comment by HenryCaiHaiying** [comment]
Thanks for the submission.  I left some comments there.
