### ISSUE TITLE
Secor unable to reset offset

### ISSUE THREAD

**Issue by kchew534** [pinterest/secor#348]
I run into this situation similar to #126 and #288 but with a difference, the topics are not deleted topics,

`2017-06-21 17:22:56 ERROR ConsumerFetcherThread:97 - [ConsumerFetcherThread-secorV2_backup_ip-172-30-29-235_2721_247-0-6], Current offset 7292 for partition [authoring-data,62] out of range; reset offset to 7204
2017-06-21 17:22:56 ERROR ConsumerFetcherThread:97 - [ConsumerFetcherThread-secorV2_backup_ip-172-30-29-235_2721_243-0-6], Current offset 112575 for partition [snowplow-events,2] out of range; reset offset to 103223`

I have checked the zookeeper node and for topic "snowplow-events" partition 2

`[zk: localhost:2181(CONNECTED) 4] get /consumers/secorV2_backup/offsets/snowplow-events/2 
112575
cZxid = 0x6092c53a9
ctime = Wed Apr 12 01:29:32 UTC 2017
mZxid = 0x60d0db1de
mtime = Wed Jun 14 20:12:39 UTC 2017
pZxid = 0x6092c53a9
cversion = 0
dataVersion = 763
aclVersion = 0
ephemeralOwner = 0x0
dataLength = 6
numChildren = 0
`
Restart Secor has no effect. Therefore I am wondering what is the best way to reset the offsets? It seems to be it is too drastic to reset the offsets of all the affected topics back to zero.

Kim

**Comment by kchew534** [comment]
How does Secor handle the out of range offsets?

I reset the partition offset manually in zookeeper and Secor started consuming messages from the partition.

**Comment by HenryCaiHaiying** [comment]
I don't think you need to manually reset the offset, the kafka high level
consumer will auto reset the offset to the earliest offset the broker has
in the range.

**Comment by kchew534** [comment]
Thanks.
