### ISSUE TITLE
Feature request: documentation on scaling secor

### ISSUE THREAD

**Issue by snowch** [pinterest/secor#357]
It would be great if the information provided in this [ticket](https://github.com/pinterest/secor/issues/182) was added to a README, or referenced from the main secor README.  I think this information is relevant for anyone running secor in production.

**Comment by HenryCaiHaiying** [comment]
This is a good idea.  Do you want to take the initiative to add a
section/paragraph in readme regarding performance tuning?  It can be a
simple paragraph describe secor process/thread and how does it map to kafka
partitions, the details can refer to that github ticket.

**Comment by snowch** [comment]
Yep. I'm very new to secor so I need to spend some time running it and ensure I fully understand the concepts, so it may take me a little while to get this done.

**Comment by HenryCaiHaiying** [comment]
This is fine, it would be a good opportunity for you to contribute to secor.
