### ISSUE TITLE
Secor partition stuck in S3 waitForUploadResult(), high CPU

### ISSUE THREAD

**Issue by juhoautio** [pinterest/secor#359]
It seems that this is already fixed in secor master since 8 Jul 2017, as aws-java-sdk-s3 was upgraded from 1.10.68 to 1.11.160: https://github.com/pinterest/secor/pull/351. Just reporting for reference.

----

Occasionally secor went to this busy loop:

```
Thread 7080: (state = IN_JAVA)
 - com.amazonaws.services.s3.transfer.internal.UploadMonitor.isDone() @bci=0, line=82 (Compiled frame; information may be imprecise)
 - com.amazonaws.services.s3.transfer.internal.UploadImpl.waitForUploadResult() @bci=6, line=60 (Compiled frame)
 - com.pinterest.secor.uploader.S3UploadHandle.get() @bci=4, line=36 (Compiled frame)
 - com.pinterest.secor.uploader.S3UploadHandle.get() @bci=1, line=28 (Compiled frame)
 - com.pinterest.secor.uploader.Uploader.uploadFiles(com.pinterest.secor.common.TopicPartition) @bci=251, line=111 (Compiled frame)
 - com.pinterest.secor.uploader.Uploader.checkTopicPartition(com.pinterest.secor.common.TopicPartition) @bci=158, line=225 (Compiled frame)
 - com.pinterest.secor.uploader.Uploader.applyPolicy() @bci=36, line=257 (Compiled frame)
 - com.pinterest.secor.consumer.Consumer.checkUploadPolicy() @bci=4, line=115 (Compiled frame)
 - com.pinterest.secor.consumer.Consumer.run() @bci=106, line=107 (Compiled frame)
```

Note that the line numbers in the stack trace match with aws-java-sdk-s3 1.11.118 – we had already upgraded to that, hoping it would fix the issue, but it didn't.

Eventually I found this issue about aws-java-sdk-s3: https://github.com/aws/aws-sdk-java/issues/1102. It describes a problem that seems exactly like the one that we had here, and there's a comment saying that the bug was fixed in 1.11.119. We are currently using 1.11.119, but obviously the version in current secor master (1.11.160) is newer than that and should also include the fix.

**Comment by juhoautio** [comment]
Assuming fixed by https://github.com/pinterest/secor/pull/351.

**Comment by satybald** [comment]
@juhoautio I'm wondering how did you able to get this stats information?

**Comment by juhoautio** [comment]
Do you mean the thread dump? I used jstack -F <pid>. kill -3 <pid> works too if you can access stdout of the process. (Both commands may require sudo depending on your situation)

**Comment by satybald** [comment]
yeah, it's a thread dump ;) silly me.
