### ISSUE TITLE
Not able to package(secor-0.24) : mvn clean -Pkafka-0.10-dev package failed

### ISSUE THREAD

**Issue by jitendrasinghsankhwar** [pinterest/secor#360]
`[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ secor ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 86 source files to /Users/jeetu/Repositories/secor-0.24/target/classes
[WARNING] /Users/jeetu/Repositories/secor-0.24/src/main/java/com/pinterest/secor/tools/TestLogMessageProducer.java: Some input files use or override a deprecated API.
[WARNING] /Users/jeetu/Repositories/secor-0.24/src/main/java/com/pinterest/secor/tools/TestLogMessageProducer.java: Recompile with -Xlint:deprecation for details.
[WARNING] /Users/jeetu/Repositories/secor-0.24/src/main/java/com/pinterest/secor/tools/ProgressMonitor.java: Some input files use unchecked or unsafe operations.
[WARNING] /Users/jeetu/Repositories/secor-0.24/src/main/java/com/pinterest/secor/tools/ProgressMonitor.java: Recompile with -Xlint:unchecked for details.
[INFO] 
[INFO] --- exec-maven-plugin:1.1:exec (default) @ secor ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 5.863 s
[INFO] Finished at: 2017-09-01T14:23:43+05:30
[INFO] Final Memory: 43M/335M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.codehaus.mojo:exec-maven-plugin:1.1:exec (default) on project secor: Result of /bin/sh -c cd /Users/jeetu/Repositories/secor-0.24 && git log --pretty=format:build_revision=%H -n1 execution is: '128'. -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoExecutionException`

**Comment by HenryCaiHaiying** [comment]
It doesn't seem I can reproduce this problem, 'mvn clean -Pkafka-0.10-dev
package' works fine for me.  And current version is already '0.25-SNAPSHOT'

**Comment by Jesse-Cameron** [comment]
Hi @HenryCaiHaiying,
I'm seeing a similar issue. In fact I am unable to build the release 0.24. However I am able to build a release for the current master branch. 
I think that it is related to [this].(https://github.com/pinterest/secor/commit/77200c8ca3eb9e4ff6ad6fe4925b74615d7e0fbf#diff-600376dffeb79835ede4a0b285078036)
Would it be possible to push a release for 0.25?

**Comment by HenryCaiHaiying** [comment]
is 0.24 packaging the wrong pom.xml?

I can try to push out the 0.25 with the current master branch.

**Comment by Jesse-Cameron** [comment]
Hi @HenryCaiHaiying,

I am actually struggling to reliably reproduce the issue I mentioned above. 
it may just be easier to push out the 0.25 release.

Thanks,
jesse

**Comment by HenryCaiHaiying** [comment]
Just cut the version 0.25, please have a try to see if that fixed your
problem.
