### ISSUE TITLE
File writer that includes message metadata

### ISSUE THREAD

**Issue by jlm3575** [pinterest/secor#362]
Is there currently a supported way to include message metadata in the delimited text output (such as offset, topic, partition, and timestamp)? After searching through the code a bit, it seems like that isn't supported without some customization on our end.

We'd like to output these fields as part of each logged message value for searching (such as indexing on it in elastic) and programatic replay (finding a particularly small window of offsets in a file). 

Have I just overlooked an obvious setting that can accomplish this, and if not, would it be something useful enough to submit in a pull request?

Thanks!

**Comment by HenryCaiHaiying** [comment]
We usually don't keep those metadata on per message level.  Some of the metatdata (e.g. topic/partition, starting offset was kept per file level).

If you want to do it on per message level, you can implement the MessageTransformer class to do that.
