### ISSUE TITLE
Test Fail When Build Project (mvn package)

### ISSUE THREAD

**Issue by josepedro** [pinterest/secor#368]
Running com.pinterest.secor.parser.DateMessageParserTest
Tests run: 5, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.09 sec <<< FAILURE! - in com.pinterest.secor.parser.DateMessageParserTest
testExtractDateUsingInputPattern(com.pinterest.secor.parser.DateMessageParserTest)  Time elapsed: 0.069 sec  <<< FAILURE!
junit.framework.ComparisonFailure: expected:<dt=[2001-07-04]> but was:<dt=[1970-01-01]>
  at junit.framework.Assert.assertEquals(Assert.java:100)
  at junit.framework.Assert.assertEquals(Assert.java:107)
  at junit.framework.TestCase.assertEquals(TestCase.java:269)
  at com.pinterest.secor.parser.DateMessageParserTest.testExtractDateUsingInputPattern(DateMessageParserTest.java:91)

Failed tests: 
  DateMessageParserTest.testExtractDateUsingInputPattern:91 expected:<dt=[2001-07-04]> but was:<dt=[1970-01-01]>

**Comment by HenryCaiHaiying** [comment]
Which timezone are you in?  We don't see this problem.

**Comment by josepedro** [comment]
Thanks for reply @HenryCaiHaiying, my timezone is BRT Brazilian Time, South America (UTC -3).

**Comment by PrayaniSingh0106** [comment]
Is this issue resolved?
