### ISSUE TITLE
java.lang.RuntimeException: Error loading configuration from secor.dev.partition.properties

### ISSUE THREAD

**Issue by john-pondr** [pinterest/secor#378]
When I configure multiple  secor.orc.message.schema topics I get the above error. In secor.common.properties I am setting up these orc.schema files and I get the error. If there are only two configured, there is no error.

```java
secor.orc.message.schema.nsm-logs=struct<schema>
secor.orc.message.schema.nsm-logs-BRO_httplog=struct<schema>
secor.orc.message.schema.nsm-logs-BRO_ssllog=struct<schema>
                                                                                     
```

Am I leaving something out?

Thanks.

**Comment by HenryCaiHaiying** [comment]
Please check this PR: https://github.com/pinterest/secor/commit/6fd65b2147be959be34525f6cb056ccbccc1d2b4

**Comment by jtryan** [comment]
@HenryCaiHaiying I see. Thanks.
You can close this
