### ISSUE TITLE
A Custom Topic Name to S3 Upload

### ISSUE THREAD

**Issue by josepedro** [pinterest/secor#379]
Hi,

I have a path in S3 with different kafka topic name. Example: in kakfa my topic name is ViewRecLog; in S3 the same topic have other name like vrl. 

So in S3 I cant rename the path. How can I put a custom topic name on Secor to upload in this path with different topic name?

**Comment by josepedro** [comment]
@HenryCaiHaiying

**Comment by HenryCaiHaiying** [comment]
This is not supported out of the box.  You can take a look at LogFilePath
to potentially modify the logic to do your custom mapping.

**Comment by josepedro** [comment]
Thank you very much @HenryCaiHaiying .
Is it welcome a pull request of this implementation?

**Comment by HenryCaiHaiying** [comment]
PR is always welcome, left a few comments in your PR

**Comment by josepedro** [comment]
Thank you very much. I will check comments and improve the code.
