### ISSUE TITLE
Regarding metrics

### ISSUE THREAD

**Issue by tamilhce** [pinterest/secor#381]
Can I have any metrics data, to check how fast secor process and store the data in  single s3.

**Comment by HenryCaiHaiying** [comment]
S3 or HDFS are fundamentally on batch operating mode, they want to client
to accumulate enough content into a file and then upload the file onto S3
or HDFS.  If the file is too small or the upload is too frequent, this
would generate many files on S3 or HDFS and it will slow down HDFS name
node.  I have seen people use secor for minutes level ingestion, not sure
whether that satisfies your needs.
