### ISSUE TITLE
Kafka authentication support?

### ISSUE THREAD

**Issue by aig787** [pinterest/secor#393]
I looked through the sample configuration and the code and didn’t see any way to use TLS authentication when connecting to the Kafka brokers. Is there any way to do this?

**Comment by gwilym** [comment]
Secor uses Kafka's SimpleConsumer API which, as far as I can tell, has no support for SSL/TLS settings, and doesn't look like it will be updated to support them according to: https://issues.apache.org/jira/browse/KAFKA-2440

This is something I've been looking into, but I can't make any timeframe guarantees, so if anyone else can tackle it feel free to jump in.

**Comment by HenryCaiHaiying** [comment]
for secor, the main data flow is going through high level consumer.  We
used simple consumer for fetch a particular message for monitoring and
partition finalization check.

TLS support is added in kafka 0.9, it should be doable to add TLS
support/configuration for secor which already supports 0.10.  Just need
someone to contribute a PR.

**Comment by gwilym** [comment]
I'm looking at adding support for loading an additional .properties file for kafka consumer configuration, so that it's not necessary to repeat all the kafka properties in secor's configs. Properties from that additional file would be merged in to and take precedence over anything inferred from secor's standard configs. That should help with situations like this, and with forward compatibility.

I was blocked by #394 though since I need to use jitpack.io to use my fork as a dependency in a docker build (and it tries and fails to build java 7, since it infers requirements from .travis.yml).

**Comment by gwilym** [comment]
I can drop java 7 support in my branch at least to unblock myself.

**Comment by HenryCaiHaiying** [comment]
How about you remove the openjdk7 in .travis.yml to unblock you?

For the properties file, how many properties are there?

**Comment by gwilym** [comment]
I'm not sure I understand the heart of the question, as the number is not predictable. It would depend on how the user needs to tune the Kafka consumer to their requirements.

In the specific case of enabling SSL support, you might for example need:

```
security.protocol=?
ssl.enabled.protocols=?
ssl.key.password=?
ssl.keystore.location=?
ssl.keystore.password=?
ssl.truststore.location=?
ssl.truststore.password=?
```

These are options I certainly need to add (at a minimum) for my own SSL with client-certificate authentication needs.

**Comment by HenryCaiHaiying** [comment]
That still seems manageable within the current secor config file.  the
kafka parameters usually takes the form of 'kafka.min.fetch.bytes' etc.  If
you want to generalize, you can say putting every config prefixed with
'kafka.' into ConsumerConfig, but that that break something.

If the properties for SSL is just 7, it's still OK to list out each one in
SecorConfig

**Comment by gwilym** [comment]
@HenryCaiHaiying I was digging into this today and am I correct in my findings here: Secor uses the "old" High Level consumer API?

Namely in `MessageReader`, which uses `Consumer.createJavaConsumerConnector`.

When I say "old", I'm only referring to the differentiation that the Kafka docs make between Kafka 0.8 and earlier, and the "new" clients brought in by Kafka 0.9, specifically around this:

http://kafka.apache.org/090/documentation.html#security_ssl

> SSL is supported only for the new Kafka Producer and Consumer, the older API is not supported. The configs for SSL will be same for both producer and consumer.

I just wanted to confirm if my understanding is correct before moving forward.

**Comment by HenryCaiHaiying** [comment]
Your understanding is probably correct.  Secor was developed during kafka
0.8 times, it won't have the new consumer API.  Upgrading secor to use the
new API should not be that difficult.
