### ISSUE TITLE
Deprecated ConsumerConnector

### ISSUE THREAD

**Issue by efeller** [pinterest/secor#397]
Looks like Secor is using a deprecated Kafka consumer API. As a result of this I am unable to use SASL options like "sasl.mechanism". VerifiableProperties reports:

2018-02-28 00:27:15,575 [Thread-6] (kafka.utils.VerifiableProperties) WARN  Property sasl.mechanism is not valid
2018-02-28 00:27:15,575 [Thread-5] (kafka.utils.VerifiableProperties) WARN  Property sasl.jaas.config is not valid
2018-02-28 00:27:15,576 [Thread-6] (kafka.utils.VerifiableProperties) WARN  Property security.protocol is not valid

Would be great if we could have a Secor version using the new consumer API and/or have some alternative solution/workaround for this. Thanks.

**Comment by orderedchaosdev** [comment]
This is the same as https://github.com/pinterest/secor/issues/393

**Comment by HenryCaiHaiying** [comment]
If guys have time, you can contribute a change to use the new consumer API,
I don't think it would be particularly difficult.

**Comment by efeller** [comment]
@HenryCaiHaiying @orderedchaosdev Thanks for the quick response. We have a fork of Secor here. I will try to find some time to write a patch and hopefully contribute it back.

**Comment by HenryCaiHaiying** [comment]
Thanks a lot, let me know when you are ready to contribute.

**Comment by chitaks** [comment]
@efeller @HenryCaiHaiying Any updates?

**Comment by igorcalabria** [comment]
@chitaks @tkaymak I'll submit a pull request this week. I'll tag you guys when its up
