### ISSUE TITLE
Secor failing to start/dying when zookeeper node is down

### ISSUE THREAD

**Issue by orderedchaosdev** [pinterest/secor#404]
I have a zookeeper quorum of 3 nodes and if any one of them goes down then secor dies even though there are still 2 of the 3 zookeeper nodes up. Also it won't start.
Just for the sake of testing I tried editing secor's list of zookeeper servers to remove that one and it still wouldn't start.

**Comment by HenryCaiHaiying** [comment]
What's the error message or stack trace?

**Comment by orderedchaosdev** [comment]
Ok it turns out in the case where it wouldn't start there was something going on with zookeeper but somehow kafka kept running even with zookeeper acting up. Zookeeper recovered when I brought back its box and unfortunately the log rotation rotated the zookeeper logs out.

So I'm going to make a new ticket for another error, since I have no way to replicate the behavior of my original issue and it appears to have in fact been zookeeper.
