### ISSUE TITLE
unable to build mvn package 

### ISSUE THREAD

**Issue by SMR39** [pinterest/secor#415]
Hi,

`mvn package`

 will result in failure always since http://packages.confluent.io/maven rep might not be working. I don't know if this is the right platform to raise this issue. But if anyone was able to build it I would appreciate some help.

```[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 38.774 s
[INFO] Finished at: 2018-05-04T14:10:53-07:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project secor: Could not resolve dependencies for project com.pinterest:secor:jar:0.26-SNAPSHOT: The following artifacts could not be resolved: io.confluent:kafka-avro-serializer:jar:2.0.1, io.confluent:kafka-schema-registry-client:jar:2.0.1,```

**Comment by HenryCaiHaiying** [comment]
I just tried myself, the build is working fine.

On Fri, May 4, 2018 at 2:22 PM, Shashi Mohan Reddy <notifications@github.com

**Comment by SMR39** [comment]
Thank you. Closing this ticket (it was  an issue with our firewall)
