### ISSUE TITLE
Feature: Native prometheus metrics

### ISSUE THREAD

**Issue by norrs** [pinterest/secor#430]
Provide native prometheus `/metrics` endpoint instead of converting statsd->prometheus metrics which is currently done in the Helm charts for kubernetes

https://prometheus.io/ supported by https://www.cncf.io/

**Comment by HenryCaiHaiying** [comment]
With https://github.com/pinterest/secor/issues/1341, there is integration with micrometer.io which supports prometheus, it should be pretty easy to add prometheus through micrometer.
