### ISSUE TITLE
Reading gzipped compressed topics

### ISSUE THREAD

**Issue by james-woods** [pinterest/secor#433]
I've checked the older issues (#255) - but I wasn't sure if anyone here tried implementing the ability to read from gzip compressed topics?

**Comment by HenryCaiHaiying** [comment]
Would gzip compressed kafka messages more or less transparent to the consumer code since the underlying consumer library will decompress the kafka message automatically?  https://stackoverflow.com/questions/19890894/kafka-message-codec-compress-and-decompress

**Comment by james-woods** [comment]
Yes you are correct, later on that page the following post makes me wonder though:
https://stackoverflow.com/a/26268555/5497956

It would explain the behaviour I am seeing - a bunch of messages (uncompressed) from topic A are being read and written by secor. Then the producer side changed the codec as message size grew too big and started sending gzip compressed messages. After the last uncompressed message in that topic was processed by secor the CPU load spiked and nothing after that got written out. 
I am currently testing the hypothesis with the console-producer and a test topic.

**Comment by james-woods** [comment]
I tested it with the console producer and the compression is handled transparently, so this can't be our problem and therefore I am closing this issue.
