### ISSUE TITLE
Next Secor version

### ISSUE THREAD

**Issue by achad4** [pinterest/secor#434]
When will v0.26 be released? There's been significant new functionality added since the last version and we'd like to move to an official release.

**Comment by JohnnyMarnell** [comment]
Yes, this would be awesome to use a maven central hosted dependency, thanks!

**Comment by HenryCaiHaiying** [comment]
I will take a look

**Comment by HenryCaiHaiying** [comment]
It took me a while to do this publish since my old laptop is gone (with the old PGP key).  I can see the new version in maven central now: http://central.maven.org/maven2/com/pinterest/secor/0.26/
