### ISSUE TITLE
Read from kafka from the very beginning.

### ISSUE THREAD

**Issue by kchew534** [pinterest/secor#438]
Not an issue. We have a use case that we need to read all kafka messages from the beginning. What Secor configuration allow me to do that?

**Comment by HenryCaiHaiying** [comment]
This config

kafka.consumer.auto.offset.reset

 corresponds to kafka's

auto.offset.reset

*https://kafka.apache.org/documentation/
<https://kafka.apache.org/documentation/>*

You can set the value to 'smallest' to read from the beginning initially
