### ISSUE TITLE
Error using secor.file.reader.writer.factory:com.pinterest.secor.io.impl.AvroParquetFileReaderWriterFactory 

### ISSUE THREAD

**Issue by vigneshsenapathy** [pinterest/secor#442]
Hey guys,

I am trying to use secor to get kafka message and convert avro to parquet format. I am using the below
secor.file.reader.writer.factory:com.pinterest.secor.io.impl.AvroParquetFileReaderWriterFactory

Below is the command i am using to run the docker container i created with the 0.26 jar's

docker run   -e DEBUG=true  -e ZOOKEEPER_QUORUM=local:2181 -e KAFKA_SEED_BROKER_HOST=local   -e AWS_ACCESS_KEY="testing"   -e AWS_SECRET_KEY="testing"   -e SECOR_S3_BUCKET=test  -e SECOR_S3_PATH=testing  -e SECOR_GROUP=raw_logs   -e SECOR_KAFKA_TOPIC_FILTER=pipeline.*  -e SECOR_MAX_FILE_SECONDS=60  -e SECOR_MESSAGE_PARSER_CLASS=com.pinterest.secor.parser.AvroMessageParser  -e SECOR_FILE_READER_WRITER_FACTORY=com.pinterest.secor.io.impl.AvroFileReaderWriterFactory -e JVM_MEMORY=2048m -e SECOR_COMPRESSION_CODEC=org.apache.hadoop.io.compress.SnappyCodec secorlocal

**secor.prod.properties**

kafka.seed.broker.host=
kafka.seed.broker.port=9092
zookeeper.quorum=
secor.kafka.group=secor_backup
secor.message.parser.class=com.pinterest.secor.parser.AvroMessageParser
secor.s3.bucket=
secor.s3.path=raw_logs/secor_backup
secor.local.path=/tmp/secor
ostrich.port=9999
secor.kafka.topic_filter=.*
secor.kafka.topic_blacklist=
secor.max.file.size.bytes=200000000
secor.max.file.age.seconds=3600
cloud.service=S3
aws.access.key=
aws.secret.key=
aws.role=
aws.proxy.http.host=
aws.proxy.http.port=
aws.region=
aws.endpoint=
aws.sse.type=
aws.sse.customer.key=
aws.sse.kms.key=
secor.s3.filesystem=s3a
zookeeper.session.timeout.ms=3000
zookeeper.sync.time.ms=200
secor.zookeeper.path=/
kafka.consumer.timeout.ms=10000
kafka.partition.assignment.strategy=range
kafka.rebalance.max.retries=
kafka.rebalance.backoff.ms=
kafka.socket.receive.buffer.bytes=
kafka.fetch.message.max.bytes=
kafka.fetch.min.bytes=
kafka.fetch.wait.max.ms=
kafka.zookeeper.path=/
kafka.dual.commit.enabled=false
kafka.offsets.storage=kafka
secor.generation=1
secor.consumer.threads=7
secor.messages.per.second=10000
secor.offsets.per.partition=10000000
secor.topic_partition.forget.seconds=600
partitioner.granularity.hour=false
partitioner.granularity.minute=true
partitioner.granularity.date.prefix=dt=
partitioner.granularity.hour.prefix=hr=
partitioner.granularity.minute.prefix=min=
partitioner.granularity.date.format=yyyyMMdd
partitioner.granularity.hour.format=HH
partitioner.granularity.minute.format=mm
partitioner.finalizer.delay.seconds=3600
secor.finalizer.lookback.periods=60
secor.local.log.delete.age.hours=-1
qubole.api.token=
hive.table.prefix=
tsdb.hostport=
monitoring.blacklist.topics=
monitoring.prefix=secor
statsd.hostport=
message.timestamp.name=timestamp
message.timestamp.name.separator=
message.timestamp.id=1
message.timestamp.type=i64
message.timestamp.input.pattern=
message.timestamp.required=true
secor.compression.codec=
secor.file.extension=
secor.file.reader.writer.factory=com.pinterest.secor.io.impl.AvroParquetFileReaderWriterFactory
secor.max.message.size.bytes=100000
secor.upload.manager.class=com.pinterest.secor.uploader.S3UploadManager
secor.parser.timezone=UTC
secor.message.transformer.class=com.pinterest.secor.transformer.IdentityMessageTransformer
secor.s3.prefix.md5hash=false
secor.s3.alter.path.date=
secor.s3.alternative.path=
secor.enable.qubole=true
secor.qubole.timeout.ms=300000
secor.kafka.upload_at_minute_mark.topic_filter=
secor.upload.minute_mark=0
kafka.consumer.auto.offset.reset=smallest
kafka.message.timestamp.className=com.pinterest.secor.timestamp.Kafka10MessageTimestamp
secor.monitoring.metrics.collector.class=com.pinterest.secor.monitoring.OstrichMetricCollector
secor.offsets.prefix=offset=
secor.file.age.youngest=true
schema.registry.url=http://local:8081
parquet.block.size=134217728
parquet.page.size=104857622
parquet.enable.dictionary=false
parquet.validation=false

**ERROR**

java.lang.RuntimeException: Failed to write message ParsedMessage{topic='testignTopic', kafkaPartition=15, offset=8, kafkaKey=, payload=testing
	at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:170)
	at com.pinterest.secor.consumer.Consumer.run(Consumer.java:98)
Caused by: org.apache.parquet.hadoop.codec.CompressionCodecNotSupportedException: codec not supported: org.apache.hadoop.io.compress.SnappyCodec
	at org.apache.parquet.hadoop.metadata.CompressionCodecName.fromCompressionCodec(CompressionCodecName.java:49)
	at com.pinterest.secor.io.impl.AvroFileReaderWriterFactory$AvroFileWriter.getCodecFactory(AvroFileReaderWriterFactory.java:141)
	at com.pinterest.secor.io.impl.AvroFileReaderWriterFactory$AvroFileWriter.<init>(AvroFileReaderWriterFactory.java:135)
	at com.pinterest.secor.io.impl.AvroFileReaderWriterFactory.BuildFileWriter(AvroFileReaderWriterFactory.java:67)
	at com.pinterest.secor.util.ReflectionUtil.createFileWriter(ReflectionUtil.java:154)
	at com.pinterest.secor.common.FileRegistry.getOrCreateWriter(FileRegistry.java:133)
	at com.pinterest.secor.writer.MessageWriter.write(MessageWriter.java:94)
	at com.pinterest.secor.consumer.Consumer.consumeNextMessage(Consumer.java:165)
	... 1 more

**Comment by vigneshsenapathy** [comment]
it was a env issue

**Comment by nut-abctech** [comment]
@vigneshsenapathy  Hi I run into the same problem. Can you guid me where did you fix it? 
I set `secor.compression.codec=org.apache.hadoop.io.compress.SnappyCodec` and get `Caused by: org.apache.parquet.hadoop.codec.CompressionCodecNotSupportedException: codec not supported: org.apache.hadoop.io.compress.SnappyCodec` error

**Comment by vigneshsenapathy** [comment]
@nut-abctech : i had to modify the code the a little to add core-site.xml in hadoop folder with snappy configuration, also i found out that my schema registry was adding topicname-value, so i took PR from one and made the change and am using that jar now...
