### ISSUE TITLE
is there a healthcheck?

### ISSUE THREAD

**Issue by vigneshsenapathy** [pinterest/secor#443]
hey guys,

I am trying to set up this service locally and want to know if there is a health check for this service

Thanks,

Vignesh

**Comment by HenryCaiHaiying** [comment]
Don't recall there is a health check since this is not really a REST
service.  Most of the time people wants to check the consumer offset lags
to see whether secor is working properly, there is a
ProgressMonitorMain.java which contains those kind of trackings, you can
take a look at that class.

**Comment by ujjwal** [comment]
What about using the Ostrich port?
