### ISSUE TITLE
Date partitioner is not working.. s3 date is being added as dt=19700101

### ISSUE THREAD

**Issue by vigneshsenapathy** [pinterest/secor#444]
Hey guys seems like the date granularity is not working correctly

partitioner.granularity.hour=false
partitioner.granularity.minute=false

partitioner.granularity.date.prefix=dt=
partitioner.granularity.hour.prefix=hr=
partitioner.granularity.minute.prefix=min=

partitioner.granularity.date.format=yyyyMMdd
partitioner.granularity.hour.format=HH
partitioner.granularity.minute.format=mm

the date in s3 gets set as **dt=19700101**

I dont know if i am missing a setting to tell it to use the current date, but seems like its using the epoch birth date which i felt was wrong. Please let me know how i can fix this. @HenryCaiHaiying  dont know if you have encountered this

Thanks

Vignesh

**Comment by HenryCaiHaiying** [comment]
By default, it gets the timestamp field in your message, do you have a
timestamp field in your message?

**Comment by vigneshsenapathy** [comment]
@HenryCaiHaiying : if i dont have the timestamp field, can i change any field to start using that field as the field...
example: message.timestamp.name=

**Comment by HenryCaiHaiying** [comment]
If you don't have your own timestamp field, you can use the timestamp from
kafka's message header (available from kafka 0.10,
https://issues.apache.org/jira/browse/KAFKA-2511), set the secor config
'kafka.useTimestamp' to true)

**Comment by vigneshsenapathy** [comment]
@HenryCaiHaiying : yes that fixed my issue. Thanks
