### ISSUE TITLE
Can kafka.seed.broker.host be set as a List of hosts

### ISSUE THREAD

**Issue by vigneshsenapathy** [pinterest/secor#445]
Hey,

I am trying to figure out for kafka.seed.broker.host can it be set a list of hosts or just one in v0.26. @HenryCaiHaiying  please let me know about this

Thanks,

Vignesh

**Comment by HenryCaiHaiying** [comment]
I think you can use a list, comma separated.

**Comment by vigneshsenapathy** [comment]
Ok thanks. I am closing the ticket
