### ISSUE TITLE
Is there a way to push the data to s3 onto a particular path without the topic name

### ISSUE THREAD

**Issue by vigneshsenapathy** [pinterest/secor#446]
Hey guys,

I am trying to figure something out with the s3 push. So currently the data is pushed to s3 under the path : 
s3://test/something/<topicname>/date=20181001/

Is there a way to do it something like this 
s3://test/something/something/date=20181001/

I dont want to use the topic name. @HenryCaiHaiying let me know if I am doing something wrong here

Thanks,

Vignesh

**Comment by HenryCaiHaiying** [comment]
That 'something' is the topic name, that's the default.  If you don't want
topic name as part of the folder structure, you will have to override
LogFilePath.getLogFilePath()

**Comment by vigneshsenapathy** [comment]
@HenryCaiHaiying : if the below parameters are used, will that still add the topic name?

# After the given date, secor will upload files to the supplied s3 alternative path
secor.s3.alter.path.date=

# An alternative S3 path for secor to upload files to
secor.s3.alternative.path=testing

**Comment by HenryCaiHaiying** [comment]
It will still have topic name in the path.  This param was designed to be
used for migration from secor to some other technologies, after the
migration cutoff date, secor will write to an alternative backup path.

Your requirement is odd, I haven't seen people doesn't want topic name in
the path.  How do you distinguish between the data from different topics?

**Comment by vigneshsenapathy** [comment]
@HenryCaiHaiying : so i am having one secor service for every topic based on the number of requests i get. So i am already telling it that one topic will go to this location. 

I just dont want to use the topic name and want to give a more friendly name if that is possible
