### ISSUE TITLE
Sending metrics to statsd not working

### ISSUE THREAD

**Issue by vigneshsenapathy** [pinterest/secor#449]
Hey,

I am trying to send metrics to statsd when secor is running. Seems like this doesnt seem to work. I am running secor in a container in bridge mode. Below are the properties i am using

statsd.hostport=172.17.0.1:8125
secor.kafka.group=secor_partition
monitoring.prefix=secor
statsd.prefixWithConsumerGroup=false

@HenryCaiHaiying : am I using the right configs

Also does progressmonitor main class need to be running for getting metrics

Thanks,

Vignesh

**Comment by HenryCaiHaiying** [comment]
Not familiar with StatsD, the code will go through StatsUtil.java, you can
turn on debug logging category to trace the problem.
