### ISSUE TITLE
No included message parser that gets timestamp from record metadata?

### ISSUE THREAD

**Issue by kennydo** [pinterest/secor#455]
Hi! I am trying to group my S3 output keys by hour and minute based on the timestamp in each Kafka record's metadata (the output of `timestamp ()` from https://kafka.apache.org/0100/javadoc/index.html?org/apache/kafka/connect/data/Timestamp.html). 

The `TimestampedMessageParser` class gets me 99.9% of the way there, to the point that all I needed to do was extend it in a super small class. I've got a branch with this ready and it's trivially simple: https://github.com/pinterest/secor/compare/master...kennydo:kedo-kafka-record-timestamp-parser?expand=1

Is there a reason the functionality (of using the timestamp in each record's metadata) isn't part of the standard set of message parsers? Could/should this simple extension of `TimestampedMessageParser` be merged upstream?

**Comment by HenryCaiHaiying** [comment]
I think what you asked for is already there.  Take a look at Kafka10MessageTimestamp.java

**Comment by kennydo** [comment]
`Kafka10MessageTimestamp` extracts the timestamp out of the Kafka record (and my secor is already configured to use it), but what I'm more interested in is making use of that timestamp data to partition partition the records into the correct hour/minute bucket, which I believe i the role of the subclasses of `MessageParser` (and `TimestampedMessageParser`).

**Comment by kennydo** [comment]
Yea, I've enabled that config parameter.

I then found out that `TimestampedMessageParser` is an abstract class, with an abstract function that is not implemented (https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/parser/TimestampedMessageParser.java#L150), so Secor is unable to instantiate it at all.

Looking closer, it looks like the actual logic in my branch isn't actually necessary. I just needed a concrete class that implements `extractTimestampMillis` to appease the compiler.

So this issue boils down to: is there a reason `TimestampedMessageParser` is abstract? Could `extractTimestampMillis` be moved elsewhere so that `TimestampedMessageParser` doesn't have to be abstract?

**Comment by HenryCaiHaiying** [comment]
The code should go to call toMills() if you already set mUseKafkaTimestamp, you are looking at the wrong path.

(mUseKafkaTimestamp) ? toMillis(message.getTimestamp())

**Comment by kennydo** [comment]
Right, the code path that leads to calling `extractTimestampMillis` is never called because I've configured it like so.

However, the definition of `extractTimestampMillis` as an abstract method in `TimestampedMessageParser` means that `TimestampedMessageParser` must be an abstract class, and abstract classes cannot be instantiated (https://docs.oracle.com/javase/tutorial/java/IandI/abstract.html).

Is there any need for `TimestampedMessageParser` to be declared an abstract class?

**Comment by HenryCaiHaiying** [comment]
This class has many concrete subclasses, did you look at them?

**Comment by kennydo** [comment]
The concrete subclasses mostly just implement `extractTimestampMillis`, with a bunch of logic that isn't relevant to me (since the timestamp I care about isn't in an Avro body or a Thrift body).

In order to have the parser use the timestamp from the Kafka record metadata, is the recommended approach to pick a random subclass of `TimestampedMessageParser` that has not overridden `getTimestampMillis`, and then enable `mUseKafkaTimestamp` so that we use the behavior of the `TimestampedMessageParser` parent class's `getTimestampMillis` path that makes use of the Kafka record timestamp?

**Comment by HenryCaiHaiying** [comment]
Why do you need to look and replace subclass's extractTimestampMillis?
Wasn't the code in superclass's toMillis() did the work for you already?

(mUseKafkaTimestamp) ? toMillis(message.getTimestamp())
