### ISSUE TITLE
Is zookeeper still required?

### ISSUE THREAD

**Issue by Danm87** [pinterest/secor#470]
Hi,
Kafka consumer client library introduced [callback interface](https://kafka.apache.org/090/javadoc/org/apache/kafka/clients/consumer/ConsumerRebalanceListener.html) for life cycle event (i.e onPartitionsRevoked) which is guaranteed  to be invoked on all consumers prior to rebalance start, which can be used in order to upload files and commit offsets before rebalance start

I know it's only been introduced in 0.9 version, but given that version or above, why is zookeeper still necessary?  

only thing I can think of is that it might apply the wrong policy (i.e upload a files smaller than required or before file age reached..

implementing this using the lifecycle event might even reduce the effort consumers need to be dealing with after rebalance, since they need to re consume the same messages again.. (assuming partitions did not reached the same consumer and trimming cannot be applied...)

Am I missing something else?

**Comment by HenryCaiHaiying** [comment]
Giving that Kafka still depends on ZK on metadata management, we probably won't tackle secor's dependency on ZK until KIP-500 is implemented: https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum
