### ISSUE TITLE
Support per-record headers

### ISSUE THREAD

**Issue by chonton** [pinterest/secor#471]
[Kafka 0.11.0.0](https://cwiki.apache.org/confluence/display/KAFKA/Release+Plan+0.11.0.0) supports [per-record headers](https://cwiki.apache.org/confluence/display/KAFKA/KIP-82+-+Add+Record+Headers).

This is a two-fold request:
- Save the additional header metadata.
- Use the header metadata to filter which messages to save.

**Comment by HenryCaiHaiying** [comment]
This is probably a useful feature.  Do you have a proposal on how to support the optional header fields?

**Comment by cricket007** [comment]
See #477
