### ISSUE TITLE
83% files are dropped before uploading to S3

### ISSUE THREAD

**Issue by jimymodi** [pinterest/secor#472]
We are just starting with secor. We are facing an issue where only 10% of messages are available in S3 when we query it through Spectrum. A prima facie, after looking at the logs and APM traces. Shows that all the Kafka messages are processed and written to the file on disk. But only 17% of the files are uploaded to S3 and rest are simply removed. Below are the logs of the files which are removed.
![image](https://user-images.githubusercontent.com/415224/49169554-fc970b00-f35f-11e8-9df0-ddc20f801166.png)

The upload policy configured is `2KB` of file size and `300` sec. Earlier till 5 hrs back. We had the file size capping at `200MB`. We reduced it, but it hasn't affected the amount of messages uploaded to S3.

One more thing we noticed is at the consumer lag in KF and ZK. We have enabled the option to save commit at both KF and ZK. But in Kafka Manager, it shows that the consumer at KF is at 0% coverage.
![image](https://user-images.githubusercontent.com/415224/49169898-e89fd900-f360-11e8-8e5f-21285166abe6.png)

Appreciate the help to further nail the issue.

**Comment by HenryCaiHaiying** [comment]
Take a look to see if it's related to: https://github.com/pinterest/secor/issues/473

**Comment by igorcalabria** [comment]
Can you check if spectrum uses a glob pattern (`*.parquet`) to query files? It may be related to https://github.com/pinterest/secor/issues/358

**Comment by jimymodi** [comment]
Thanks for the pointers.
Our issue was with the configuration of below options:

**Before**
```
zookeeper.session.timeout.ms=3000
zookeeper.sync.time.ms=200
kafka.offsets.storage=kafka

```
**After**
```
zookeeper.session.timeout.ms=6000
zookeeper.sync.time.ms=2000
kafka.offsets.storage=zookeeper
```
