### ISSUE TITLE
Should SecorKafkaMessageIterator CommitFailedException be rethrown?

### ISSUE THREAD

**Issue by ujjwal** [pinterest/secor#473]
What if it can't commit the offset? 

https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/reader/SecorKafkaMessageIterator.java#L159

**Comment by HenryCaiHaiying** [comment]
The author probably thinks this is a retriable error, but LOG.trace might hide the real problem.  LOG.info or LOG.warn might be better in this case.  If you want, you can submit a PR to change the logging category.
