### ISSUE TITLE
Remove or truncate payload and kafkaKey in Message.fieldsToString()

### ISSUE THREAD

**Issue by glasser** [pinterest/secor#474]
Sometimes, a stringified Message or ParsedMessage ends up in, say, a RuntimeException that is thrown and printed at crash time.  These classes contain kafkaKey and (especially) payload which can be very long (kilobytes or megabytes in our use case), multiple lines, contain PII, etc. I'd like to either truncate these fields to a much smaller length (say 1K) or even leave the fields out entirely. Does anything depend on these fields being fully included in toString?

**Comment by HenryCaiHaiying** [comment]
I think you can do two logging lines, one logs the truncated message, one logs the un-truncated (original) message on DEBUG category.  There might be people want to see the whole message.

**Comment by glasser** [comment]
In practice this is showing up less in INFO logs and more RuntimeExceptions.  Stuff like: https://github.com/pinterest/secor/blob/1fa9d74976e66002642d46b9e6480587dd51e86c/src/main/java/com/pinterest/secor/consumer/Consumer.java#L170

Actually, hmm, at least looking for cases where toString is called directly on an variable of type Message or ParsedMessage (vs some more generic place), that particular line looks like the worst offender. Other places where Secor adds message.toString() to a RuntimeException are parse failures, which do legitimately seem like places you might be curious about the full payload.  But that line is likely to be an IO issue, or an IllegalStateException being thrown by the File.deleteOnExit in FileRegistry if we're already shutting down, or something.  So maybe add a new toTruncatedString() to Message/ParsedMessage which is used in this particular exception, with a debug log before it?

Happy to send the PR, just curious if you think that's a good choice.

**Comment by HenryCaiHaiying** [comment]
I think it would be a good idea to add a PR for truncated message, thanks.
