### ISSUE TITLE
Trimming partitioned files cause log drop

### ISSUE THREAD

**Issue by sayuan** [pinterest/secor#476]
When `trimFiles`[1] happen, it need the `offset`[2] of each massage.
[1]: https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/uploader/Uploader.java#L258
[2]: https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/uploader/Uploader.java#L177

If one partition has multiple (partitioned) files, it will retrieve the incorrect offset.
https://github.com/pinterest/secor/blob/master/src/main/java/com/pinterest/secor/io/impl/DelimitedTextFileReaderWriterFactory.java#L91

Therefore, it will filter out logs incorretctly and cause the log drop.

**Comment by HenryCaiHaiying** [comment]
I think this problem is specific to DelimitedTextFileReaderWriter which
didn't have a proper management of kafka offsets.

**Comment by sayuan** [comment]
Here is the list of Reader which doesn't manage the offset correctly:
```
# git grep -l offset++ src/main/java/com/pinterest/secor/io/impl
src/main/java/com/pinterest/secor/io/impl/AvroFileReaderWriterFactory.java
src/main/java/com/pinterest/secor/io/impl/AvroParquetFileReaderWriterFactory.java
src/main/java/com/pinterest/secor/io/impl/JsonORCFileReaderWriterFactory.java
src/main/java/com/pinterest/secor/io/impl/ProtobufParquetFileReaderWriterFactory.java
src/main/java/com/pinterest/secor/io/impl/ThriftParquetFileReaderWriterFactory.java```

**Comment by HenryCaiHaiying** [comment]
I think the problem is DelimitedTextFileReaderWriter didn't store the
original kafka offset in the file so it couldn't skip to the right offset
when trimming happens.
