### ISSUE TITLE
configure secor logging

### ISSUE THREAD

**Issue by dendres** [pinterest/secor#67]
When invoking com.pinterest.secor.main.ConsumerMain
I include the suggested logging configuration paramater:
-Dlog4j.configuration=log4j.prod.properties

strace tells me that the app never tries to read log4j.prod.properties

$ strace -f -e trace=file java -ea -Dsecor_group=secor_backup -Dlog4j.configuration=log4j.prod.properties -Dconfig=secor.prod.backup.properties -cp secor-0.1-SNAPSHOT.jar:lib/\* com.pinterest.secor.main.ConsumerMain 2> out.log
$ grep properties out.log | grep log
[pid  6469] open("/usr/lib/jvm/java-7-openjdk-amd64/jre/lib/logging.properties", O_RDONLY) = 95

The strace is successful and other properties files related to logging are being read. 
Unfortunately, the specified log4j.prod.properties is never read. 

$ java -version
java version "1.7.0_65"
OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

**Comment by richid** [comment]
I was having similar issues with SLF4J complaining that no log appenders were found. I ended up getting this working by using the follow system property:

`-Dlog4j.configuration="file:/full/path/to/log4j.prod.properties"`

**Comment by yyejun** [comment]
I think log4j.properties needs to be in classpath.

**Comment by jgagnon1** [comment]
Just went through that and wanted to confirm that you need to put the full path with the `file` prefix.

`-Dlog4j.configuration="file:///full/path/to/log4j.prod.properties"`
