### ISSUE TITLE
Why secor need zk?

### ISSUE THREAD

**Issue by wjzhangcsu** [pinterest/secor#673]
Which state information needs to be obtained in zk?

**Comment by HenryCaiHaiying** [comment]
secor needs zk for two things:
    1. offset management for consumer offsets, this is probably no longer
needed with the new kafka high level consumer
    2. persisted offsets for s3 upload file for exact-once uploading, I
think this is still needed.

**Comment by wjzhangcsu** [comment]
@HenryCaiHaiying , thanks~

**Comment by HenryCaiHaiying** [comment]
Kafka currently still needs ZK for it's metadata management, once Kafka can get rid of dependency on ZK through https://cwiki.apache.org/confluence/display/KAFKA/KIP-500%3A+Replace+ZooKeeper+with+a+Self-Managed+Metadata+Quorum, we can take a look at secor code to remove the dependency as well.
