### ISSUE TITLE
LogFilePrinter displaying extra characters

### ISSUE THREAD

**Issue by estezz** [pinterest/secor#69]
When using the LogFilePrinter secor is not using length to trim the byte array from the BytesWritable.

If you load these 2 messages into kafka.
{"array":[1,2,3],"boolean":true,"null":null,"dog":"brown","dog2":"brown","dog3":"brown","dog4":"brown","dog5":"brown","dog6":"brown","dog7":"brown","dog8":"brown","dog9":"brown","dog10":"brown","dog11":"brown","number":123,"object":{"a":"b","c":"d","e":"f"},"string":"Hello World"}

{"array":[1,2,3],"boolean":true,"null":null,"number":123,"object":{"a":"b","c":"d","e":"f"},"string":"Hello World"}

The LogFilePrinter will display this. I put the extra data in bold on line 14
13: {"array":[1,2,3],"boolean":true,"null":null,"dog":"brown","dog2":"brown","dog3":"brown","dog4":"brown","dog5":"brown","dog6":"brown","dog7":"brown","dog8":"brown","dog9":"brown","dog10":"brown","dog11":"brown","number":123,"object":{"a":"b","c":"d","e":"f"},"string":"Hello World"}

14: {"array":[1,2,3],"boolean":true,"null":null,"number":123,"object":{"a":"b","c":"d","e":"f"},"string":"Hello World"}**n","dog6":"brown","dog7":"brown","dog8":"brown","dog9":"brown","dog10":"brown","dog11":"brown","number":123,"object":{"a":"b","c":"d","e":"f"},"string":"Hello World"}**

This is the bug in Hadoop https://issues.apache.org/jira/browse/HADOOP-6298
**The bold shows the fix for this**
package com.pinterest.secor.tools;

import com.pinterest.secor.util.FileUtil;
import org.apache.hadoop.conf.Configuration;
import org.apache.hadoop.fs.FileSystem;
import org.apache.hadoop.fs.Path;
import org.apache.hadoop.io.BytesWritable;
import org.apache.hadoop.io.LongWritable;
import org.apache.hadoop.io.SequenceFile;

import java.io.IOException;

/**
- Log file printer displays the content of a log file.
  *
- @author Pawel Garbacki (pawel@pinterest.com)
  */
  public class LogFilePrinter {
  private boolean mPrintOffsetsOnly;
  
  public LogFilePrinter(boolean printOffsetsOnly) throws IOException {
      mPrintOffsetsOnly = printOffsetsOnly;
  }
  
  public void printFile(String path) throws Exception {
      FileSystem fileSystem = FileUtil.getFileSystem(path);
      Path fsPath = new Path(path);
      SequenceFile.Reader reader = new SequenceFile.Reader(fileSystem, fsPath,
              new Configuration());
      LongWritable key = (LongWritable) reader.getKeyClass().newInstance();
      BytesWritable value = (BytesWritable) reader.getValueClass().newInstance();
      System.out.println("reading file " + path);
      while (reader.next(key, value)) {
          if (mPrintOffsetsOnly) {
              System.out.println(Long.toString(key.get()));
          } else {
              byte[] nonPaddedBytes = new byte[value.getLength()];
              **System.arraycopy(value.getBytes(), 0, nonPaddedBytes, 0, value.getLength());
              System.out.println(Long.toString(key.get()) + ": " + new String(nonPaddedBytes));**
          }
  
  ```
  }
  ```
  
  }
  }

**Comment by pgarbacki** [comment]
Thanks for identifying the issue, @estezz 

Would you mind cutting a PR with the fix? I can do it as well if it's a major inconvenience.

**Comment by estezz** [comment]
You should have the pull request.  How do I become a official contributor?

**Comment by pgarbacki** [comment]
@estezz add yourself to README.md
