### ISSUE TITLE
Support for schema evolution while using Parquet Files (for Avro messages) output

### ISSUE THREAD

**Issue by 0rainingdays0** [pinterest/secor#703]
I am trying to back up my avro topics to azure blob storage. But for one of my topic I am getting class cast exception. This because of an additional field added to the topic. My question is weather secor support schema evolution while using Parquet Files (for Avro messages) as output.

**Comment by HenryCaiHaiying** [comment]
I think for avro messages, you should be able to use the old schema to parse the new messages, is the problem on parquet side?
