### ISSUE TITLE
Locale-dependent test

### ISSUE THREAD

**Issue by andrioni** [pinterest/secor#78]
Hello! [This DateMessageParser test](https://github.com/pinterest/secor/blob/master/src/test/java/com/pinterest/secor/parser/DateMessageParserTest.java#L53-L55) is locale-dependent, and fails in non-English locales (which is how I discovered it!).

What would the best solution for this issue? Adding a new locale parameter (e.g. `message.timestamp.locale`) or just removing the test?

**Comment by pgarbacki** [comment]
Although it is a bit ugly from the stylistic point of view, you could
change the default locale
<http://docs.oracle.com/javase/7/docs/api/java/util/Locale.html#setDefault(java.util.Locale)>
for that test, and then change it back.

**Comment by pgarbacki** [comment]
@zago would you mind taking a look at this test?
