### ISSUE TITLE
Support IAM temporary credentials from ec2 instance profile / role

### ISSUE THREAD

**Issue by danharvey** [pinterest/secor#8]
We're looking at deploying secor on ec2 to push data to our S3 buckets but we're currently using ec2 instance profiles to allow instances to get temporary credentials to access AWS resources rather than hard-coding keys in config.

We've had a look at modifying secor to support this but it doesn't seem simple due to using the Hadoop S3 abstractions as they use an old version of jets3t that doesn't support passing the additional token needed to use the temporary credentials.

So it seems we can wait for Hadoop to finally work this this:
 - https://issues.apache.org/jira/browse/HADOOP-9680
 - https://issues.apache.org/jira/browse/HADOOP-9384

Or have an uploader that uses the native AWS Java SDK which supports this already (including token refreshing, etc..)

**Comment by a86c6f7964** [comment]
Why did this get closed? Are y'all deciding to not do this or does hadoop work with it now?

**Comment by pgarbacki** [comment]
I feel it is more sensible to stick with a solution that supports other file systems (as mentioned in the comments above). Hopefully, this will get fixed in the hadoop API at some point.

**Comment by pgarbacki** [comment]
In fact, it looks like one of the hadoop issues mentioned in the original post has been recently patched:
https://issues.apache.org/jira/browse/HADOOP-9384

**Comment by yyejun** [comment]
Any reason not use s3a instead?

**Comment by pgarbacki** [comment]
There are concerns related to forward compatibility: https://github.com/pinterest/secor/pull/87
