### ISSUE TITLE
automatic deleting local files

### ISSUE THREAD

**Issue by foovungle** [pinterest/secor#83]
Does Secor delete local files that have been uploaded to s3? I saw this setting:
```
# If greater than 0, upon starup Secor will clean up directories and files under secor.local.path
# that are older than this value.
secor.local.log.delete.age.hours=-1
```

But the documentation seems to say it only does the check on startup. Is/will there be a setting for doing cleanup by age during runtime?

Thx

**Comment by pgarbacki** [comment]
Files are normally cleaned up after they got uploaded to s3. secor.local.log.delete.age.hours is useful if you frequently restart Secor leaving garbage behind.
