### ISSUE TITLE
secor 2.0- GO Language when are you releasing

### ISSUE THREAD

**Issue by aakashagarwal** [pinterest/secor#859]
We are using java secor extensively but facing performance issues, I heard pinterest has developed same tool in go. We can contribute and test it here if you open it up.

**Comment by HenryCaiHaiying** [comment]
Our new tool is called merced which did many improvements in resource
allocation and management of many topic/ingestion pipelines, but it's also
written in Java.

**Comment by aakashagarwal** [comment]
Any plans to open source? After review we can test, deploy and contribute to this projects.

**Comment by georgehdd** [comment]
@HenryCaiHaiying is merced open source?
