### ISSUE TITLE
Secor failure upload policy

### ISSUE THREAD

**Issue by itachi90** [pinterest/secor#86]
If max file age set to more than 24 hours Secor fails to upload files when using DateMessageParser or other parsers that partition message based on date. Probably because every new day there will be new file created in each topic partition that renews the result of getModificationAgeSec method in FileRegistry.

**Comment by pgarbacki** [comment]
The upload should not be delayed indefinitely. In the worst case, there could be a delay of 48h. For details, see https://groups.google.com/forum/#!topic/secor-users/wxO0Eb83_R4

**Comment by itachi90** [comment]
I understand how secor uses the age of newest file in partition for the upload policy, but if I configure secor to use a DateMessageParser, when the new day comes(the timestamp of messages extract local machine time), a new file will be created in the same partition to store messages of the new date, will this behavior set file age zero everyday? Will it constrain secor upload policy?

**Comment by pgarbacki** [comment]
I think you are right. It is rather unconventional to set the upload delay to a value larger than the partition time interval but there is a corner case here that is not supported.

**Comment by itachi90** [comment]
Thanks for confirmation. I was thinking about some use cases that when the total message throughput is small, it is better to batch messages for longer time to create larger and lesser file on object store server, cause when the number of objects is large on S3 or other object store such as Swift, the performance may suffer.
