### ISSUE TITLE
Restoring Data

### ISSUE THREAD

**Issue by thalescm** [pinterest/secor#88]
The default behaviour of Secor is to backup data to Amazon S3.  
What about restoring this data? I mean, what if a cluster or a broker breaks, you loose all the log data or it is deleted and you need it again?  

Does this project also serves for this??

Thanks in advance

**Comment by pgarbacki** [comment]
Are you asking about restoring kafka data from Secor? Secor Does not come with a tool to do that but writing a simple kafka producer that goes over the logs and replays them shouldn't be hard to implement.

**Comment by OneCricketeer** [comment]
Log replay is only a partial solution, and makes some strong assumptions about original topic/producer configuration.
