### ISSUE TITLE
Secor not safe to null payloads

### ISSUE THREAD

**Issue by estezz** [pinterest/secor#92]
**com.pinterest.secor.message.Message.fieldsToString not null safe.
Somehow we got a null payload in kafka, and secor throws a NullPointerException.**

15/05/11 19:12:24 ERROR main.ConsumerMain: Thread Thread[Thread-4,5,main] failed
java.lang.NullPointerException
    at java.lang.String.<init>(String.java:554)
    at com.pinterest.secor.message.Message.fieldsToString(Message.java:35)
    at com.pinterest.secor.message.Message.toString(Message.java:44)
    at java.lang.String.valueOf(String.java:2981)
    at java.lang.StringBuilder.append(StringBuilder.java:131)
    at com.pinterest.secor.reader.MessageReader.read(MessageReader.java:141)
    at com.pinterest.secor.consumer.Consumer.run(Consumer.java:92)

**I would fix this myself but I can no longer build secor due to twitter dependencies that are no longer available.**

[ERROR] Failed to execute goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile (thrift-sources) on project secor: Execution thrift-sources of goal com.twitter:maven-finagle-thrift-plugin:0.0.9:compile failed: A required class was missing while executing com.twitter:maven-finagle-thrift-plugin:0.0.9:compile: com/google/common/collect/ImmutableSet

I tried lots of ways to find the dependencies but nothing would fix it completely.

**I am a committer on this project and really would like to contribute some more, if someone could help with the dependency problems**

**Comment by ramkivenkatachalam** [comment]
i did a clone, blew away my .m2 cache and was able to rebuild successfully. Can you try the same to see if you are still having issues?

**Comment by estezz** [comment]
I moved my .m2 to .m2.save, cloned a new version of secor and did a build.
I am building with java version "1.7.0_60"

I get this error.
[ERROR] /home/lwoessner/workspace/secor/target/generated-sources/thrift/gen-java/com/pinterest/secor/thrift/TestMessage.java:[35,33] error: package com.twitter.finagle.thrift does not exist

do you have something in your settings.xml that would change things?

Leo

**Comment by ramkivenkatachalam** [comment]
Leo,

Not sure what is going on with your environment?

My setup:
java -version
java version "1.7.0_67"
Java(TM) SE Runtime Environment (build 1.7.0_67-b01)
Java HotSpot(TM) 64-Bit Server VM (build 24.65-b04, mixed mode)

nothing in settings.xml 

What is the line in the generated file TestMessage.java? Is maven still having trouble finding finagle-thrift jar?

**Comment by estezz** [comment]
I commented out that line of the generated TestMessage.java and did a mvn package and it is find.  Not sure how to get this line to be left out by default.

**Comment by sanear** [comment]
Just throwing my hat into the ring to say I'm having this trouble on the dev branch as well. I just updated my fork, and the behavior continues. 

Either of you guys make progress the original issue with the `Failed toString() invocation on an object of type [com.pinterest.secor.message.Message]` error?

**Comment by llamahunter** [comment]
Am able to build on OSX 10.10.5, but cannot build on CentOS 7.1. Get the same errors as above about missing com.twitter.finagle.thrift

**Comment by llamahunter** [comment]
Ditto on this null payload problem.  I have changes in my tree to fix this, as I did not see that someone had already submitted a pull (112), but that pull seems 'bad'?  What's the status on fixing this?  Should I submit another pull request?

**Comment by estezz** [comment]
Richard, did you make the same change I did?

public Message(String topic, int kafkaPartition, long offset, byte[]
payload) {

mTopic = topic;
mKafkaPartition = kafkaPartition;
mOffset = offset;
mPayload = payload;

if (mPayload == null) {
   mPayload = new byte[0];
}
    }

I don;t know why that changed broke the integration tests.  But if you can
get it to work, go for it.  A friend at another company and I are both
running my fix.
Let me know how it goes.

Leo

On Wed, Aug 19, 2015 at 10:32 AM, Richard Lee <notifications@github.com>
wrote:

> Ditto on this null payload problem. I have changes in my tree to fix this,
> as I did not see that someone had already submitted a pull (112), but that
> pull seems 'bad'? What's the status on fixing this? Should I submit another
> pull request?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pinterest/secor/issues/92#issuecomment-132685977>.
>



-- 
Leo Woessner

Sign up for Uber at this link and we both get free rides :)
*https://www.uber.com/invite/ern6a <https://www.uber.com/invite/ern6a>*

**Comment by llamahunter** [comment]
I made a similar change.  https://github.com/TiVo/secor/tree/handle-null-payloads <https://github.com/TiVo/secor/tree/handle-null-payloads>

However, I preserved the null value.  It’s important to know when the value is null to detect tombstones, but I suspect a zero length byte field is pretty close to null, and code could be written to deal with that, instead.  Also, your approach doesn’t require fixing the FileWriter.

Richard
Key ID: 3BDED925D4F316B3

**Comment by estezz** [comment]
Richard,

I think I like your solution better.  Can you make a pull request to
secor?  Then I will get your changes.


Thanks for working with me

Leo

On Wed, Aug 19, 2015 at 2:08 PM, Richard Lee <notifications@github.com>
wrote:

> I made a similar change.
> https://github.com/TiVo/secor/tree/handle-null-payloads <
> https://github.com/TiVo/secor/tree/handle-null-payloads>
>
> However, I preserved the null value. It’s important to know when the value
> is null to detect tombstones, but I suspect a zero length byte field is
> pretty close to null, and code could be written to deal with that, instead.
> Also, your approach doesn’t require fixing the FileWriter.
>
> Richard
> Key ID: 3BDED925D4F316B3
>
>
>
> > On Aug 19, 2015, at 11:50 AM, estezz <notifications@github.com> wrote:
> >
> > Richard, did you make the same change I did?
> >
> > public Message(String topic, int kafkaPartition, long offset, byte[]
> > payload) {
> >
> > mTopic = topic;
> > mKafkaPartition = kafkaPartition;
> > mOffset = offset;
> > mPayload = payload;
> >
> > if (mPayload == null) {
> > mPayload = new byte[0];
> > }
> > }
> >
> > I don;t know why that changed broke the integration tests. But if you can
> > get it to work, go for it. A friend at another company and I are both
> > running my fix.
> > Let me know how it goes.
> >
> > Leo
> >
> > On Wed, Aug 19, 2015 at 10:32 AM, Richard Lee <notifications@github.com>
> > wrote:
> >
> > > Ditto on this null payload problem. I have changes in my tree to fix
> this,
> > > as I did not see that someone had already submitted a pull (112), but
> that
> > > pull seems 'bad'? What's the status on fixing this? Should I submit
> another
> > > pull request?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pinterest/secor/issues/92#issuecomment-132685977>.
> > >
> >
> >
> >
> > --
> > Leo Woessner
> >
> > Sign up for Uber at this link and we both get free rides :)
> > *https://www.uber.com/invite/ern6a <https://www.uber.com/invite/ern6a>*
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/pinterest/secor/issues/92#issuecomment-132740226>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pinterest/secor/issues/92#issuecomment-132764588>.
>



-- 
Leo Woessner

Sign up for Uber at this link and we both get free rides :)
*https://www.uber.com/invite/ern6a <https://www.uber.com/invite/ern6a>*

**Comment by pgarbacki** [comment]
@llamahunter indeed, you should consider proposing a change to the mainstream secor branch. I think it is a useful extension.

**Comment by estezz** [comment]
Richard are you planing to make a pull request for your fix to the null
payload?  If not I might follow your pattern and request a pull.


Leo

On Wed, Aug 19, 2015 at 2:08 PM, Richard Lee <notifications@github.com>
wrote:

> I made a similar change.
> https://github.com/TiVo/secor/tree/handle-null-payloads <
> https://github.com/TiVo/secor/tree/handle-null-payloads>
>
> However, I preserved the null value. It’s important to know when the value
> is null to detect tombstones, but I suspect a zero length byte field is
> pretty close to null, and code could be written to deal with that, instead.
> Also, your approach doesn’t require fixing the FileWriter.
>
> Richard
> Key ID: 3BDED925D4F316B3
>
>
>
> > On Aug 19, 2015, at 11:50 AM, estezz <notifications@github.com> wrote:
> >
> > Richard, did you make the same change I did?
> >
> > public Message(String topic, int kafkaPartition, long offset, byte[]
> > payload) {
> >
> > mTopic = topic;
> > mKafkaPartition = kafkaPartition;
> > mOffset = offset;
> > mPayload = payload;
> >
> > if (mPayload == null) {
> > mPayload = new byte[0];
> > }
> > }
> >
> > I don;t know why that changed broke the integration tests. But if you can
> > get it to work, go for it. A friend at another company and I are both
> > running my fix.
> > Let me know how it goes.
> >
> > Leo
> >
> > On Wed, Aug 19, 2015 at 10:32 AM, Richard Lee <notifications@github.com>
> > wrote:
> >
> > > Ditto on this null payload problem. I have changes in my tree to fix
> this,
> > > as I did not see that someone had already submitted a pull (112), but
> that
> > > pull seems 'bad'? What's the status on fixing this? Should I submit
> another
> > > pull request?
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pinterest/secor/issues/92#issuecomment-132685977>.
> > >
> >
> >
> >
> > --
> > Leo Woessner
> >
> > Sign up for Uber at this link and we both get free rides :)
> > *https://www.uber.com/invite/ern6a <https://www.uber.com/invite/ern6a>*
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/pinterest/secor/issues/92#issuecomment-132740226>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pinterest/secor/issues/92#issuecomment-132764588>.
>



-- 
Leo Woessner

Sign up for Uber at this link and we both get free rides :)
*https://www.uber.com/invite/ern6a <https://www.uber.com/invite/ern6a>*

**Comment by llamahunter** [comment]
It’s unclear to me that my approach is better than yours, as, eventually, the value that both of us will write out to the archive via SequenceFile is a zero length array.  I am actually partial to your approach, as it is a single change that protects any other code in secor from having to check for a null value, as the payload variable is always non-null, if sometimes sort of pointless, being zero bytes.  For instance, I think my approach needs an additional code change to make the DelimitedTextFileWriter not crash on null.

The only optimization I might make to your approach is to have a static final zero byte array in the Message class that is used for null payloads so that there’s not object churn making new ones of these.  See, for instance, the implementation of the org.apache.hadoop.io.BytesWritable class.

**Comment by estezz** [comment]
I can see it both ways, but my change is breaking the secor integration
tests and I do not know how to fix that.  I was hoping your approach would
pass the integration tests.
I will try some more.

here is the integration failures if you are interested.

https://travis-ci.org/pinterest/secor/builds/75126991

On Wed, Aug 26, 2015 at 10:53 AM, Richard Lee <notifications@github.com>
wrote:

> It’s unclear to me that my approach is better than yours, as, eventually,
> the value that both of us will write out to the archive via SequenceFile is
> a zero length array. I am actually partial to your approach, as it is a
> single change that protects any other code in secor from having to check
> for a null value, as the payload variable is always non-null, if sometimes
> sort of pointless, being zero bytes. For instance, I think my approach
> needs an additional code change to make the DelimitedTextFileWriter not
> crash on null.
>
> The only optimization I might make to your approach is to have a static
> final zero byte array in the Message class that is used for null payloads
> so that there’s not object churn making new ones of these. See, for
> instance, the implementation of the org.apache.hadoop.io.BytesWritable
> class.
>
>
>
> > On Aug 26, 2015, at 9:39 AM, estezz <notifications@github.com> wrote:
> >
> > Richard are you planing to make a pull request for your fix to the null
> > payload? If not I might follow your pattern and request a pull.
> >
> >
> > Leo
> >
> > On Wed, Aug 19, 2015 at 2:08 PM, Richard Lee <notifications@github.com>
> > wrote:
> >
> > > I made a similar change.
> > > https://github.com/TiVo/secor/tree/handle-null-payloads <
> > > https://github.com/TiVo/secor/tree/handle-null-payloads>
> > >
> > > However, I preserved the null value. It’s important to know when the
> value
> > > is null to detect tombstones, but I suspect a zero length byte field is
> > > pretty close to null, and code could be written to deal with that,
> instead.
> > > Also, your approach doesn’t require fixing the FileWriter.
> > >
> > > Richard
> > > Key ID: 3BDED925D4F316B3
> > >
> > >
> > >
> > > > On Aug 19, 2015, at 11:50 AM, estezz <notifications@github.com>
> wrote:
> > > >
> > > > Richard, did you make the same change I did?
> > > >
> > > > public Message(String topic, int kafkaPartition, long offset, byte[]
> > > > payload) {
> > > >
> > > > mTopic = topic;
> > > > mKafkaPartition = kafkaPartition;
> > > > mOffset = offset;
> > > > mPayload = payload;
> > > >
> > > > if (mPayload == null) {
> > > > mPayload = new byte[0];
> > > > }
> > > > }
> > > >
> > > > I don;t know why that changed broke the integration tests. But if
> you can
> > > > get it to work, go for it. A friend at another company and I are both
> > > > running my fix.
> > > > Let me know how it goes.
> > > >
> > > > Leo
> > > >
> > > > On Wed, Aug 19, 2015 at 10:32 AM, Richard Lee <
> notifications@github.com>
> > > > wrote:
> > > >
> > > > > Ditto on this null payload problem. I have changes in my tree to
> fix
> > > this,
> > > > > as I did not see that someone had already submitted a pull (112),
> but
> > > that
> > > > > pull seems 'bad'? What's the status on fixing this? Should I submit
> > > another
> > > > > pull request?
> > > > >
> > > > > —
> > > > > Reply to this email directly or view it on GitHub
> > > > > <
> https://github.com/pinterest/secor/issues/92#issuecomment-132685977>.
> > > > >
> > > >
> > > >
> > > >
> > > > --
> > > > Leo Woessner
> > > >
> > > > Sign up for Uber at this link and we both get free rides :)
> > > > *https://www.uber.com/invite/ern6a <
> https://www.uber.com/invite/ern6a>*
> > > > —
> > > > Reply to this email directly or view it on GitHub <
> > > https://github.com/pinterest/secor/issues/92#issuecomment-132740226>.
> > >
> > > >
> > >
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <https://github.com/pinterest/secor/issues/92#issuecomment-132764588>.
> > >
> >
> >
> >
> > --
> > Leo Woessner
> >
> > Sign up for Uber at this link and we both get free rides :)
> > *https://www.uber.com/invite/ern6a <https://www.uber.com/invite/ern6a>*
> > —
> > Reply to this email directly or view it on GitHub <
> https://github.com/pinterest/secor/issues/92#issuecomment-135100755>.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pinterest/secor/issues/92#issuecomment-135106538>.
>



-- 
Leo Woessner

Sign up for Uber at this link and we both get free rides :)
*https://www.uber.com/invite/ern6a <https://www.uber.com/invite/ern6a>*
