### ISSUE TITLE
Is there a way to store month as subfolder of year,  date as subfolder as month ?

### ISSUE THREAD

**Issue by chandramohan11mx08** [pinterest/secor#920]
With the help of current docuement I was able to store files in **dt=2019-09-06** -> **hr=01** format. I want a folder structure like year->month->date->hour. Example **yr=2019->mm=09->dd=06->hr=01**

Use case is like, we push request logs into S3 and search may be performed later using AWS Athena service, which takes s3 path as argument. Now If I want to take a count on like number of requests per months I cannot give a particular path as input to load data from S3.

**Comment by lovenishgoyal** [comment]
Hi,

You can extend TimestampedMessageParser class and override "String[] extractPartitions(Message message)". 
return of this method is a String array so arr[0] = "yr=2019" , arr[1] = "mm=09", arr[2] = "dd=06", arr[3] = "hr=01"

**Comment by chandramohan11mx08** [comment]
Thanks, I have extended JsonMessageParser and overridden extractPartitions(Message message) method. It works.
