### ISSUE TITLE
S3 sdk upgrade to 2.x to support netty based NIO

### ISSUE THREAD

**Issue by holyshipt** [pinterest/secor#925]
Hi, We are doing some high data volume upload test, it seems reached bottleneck at ~100MB/s on our setup using parquet/profobuf writer. Currently we plan to upgrade s3 sdk to leverage nio for higher work load. Wondering if you have any plan on upgrade aws sdk to 2.x to benefit from nio?

**Comment by HenryCaiHaiying** [comment]
No particular plan as far as I know.  But you are welcome to try that upgrade, if there is no API change, it should be a straightforward work.

**Comment by holyshipt** [comment]
Thanks. Will update you our findings here.
