### ISSUE TITLE
SecorSchemaRegisteryClient serialization/deserialization Error [SerializationException: Unknown magic byte error!]

### ISSUE THREAD

**Issue by breadpowder** [pinterest/secor#950]
**1. Error Description** :

Version 0.28. We saw the error in production,

java.lang.RuntimeException: Failed to apply upload policy
        at com.pinterest.secor.consumer.Consumer.checkUploadPolicy(Consumer.java:182)
        at com.pinterest.secor.consumer.Consumer.run(Consumer.java:163)
Caused by: org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
2019-09-20 10:48:52,802 [main] (com.pinterest.secor.common.SecorConfig$1:67) INFO  Configu

**2. Reproduce**:
 I wrote a test to reproduce the error and the test case can be put into AvroParquetFileReaderWriterFactoryTest.

    @Test
    public void testAvroParquetReadWriterRoundTripWithConfluentSchemaRegister() throws Exception{

        Schema schema = SchemaBuilder.record("UnitTestRecord")
                .fields()
                .name("data").type().stringType().noDefault()
                .name("timestamp").type().nullable().longType().noDefault()
                .endRecord();

        GenericRecordBuilder builder = new GenericRecordBuilder(schema);
        msg1 = builder.set("data", "foo").set("timestamp", 1467176315L).build();
        writer = new SpecificDatumWriter(schema);
        KeyValue kv1 = (new KeyValue(23232, AvroSerializer.serialize(writer, msg1)));

        SecorSchemaRegistryClient secorSchemaRegistryClient = new SecorSchemaRegistryClient(config);

        Exception e = null;
        try {
            secorSchemaRegistryClient.deserialize("test-avro-topic", kv1.getValue());
        } catch (SerializationException se){
            se.printStackTrace();
            e = se;
        }

        assertEquals(null, e);
    }

**3. To Fix**:
Looks to us that SecorSchemaRegistryClient use AvroSerializer for serialization. However, this client uses KafkaAvroDeserializer (from confluent) for deserialization.  Since KafkaAvroDeserializer requires a payload follow certain format (see https://docs.confluent.io/3.2.0/schema-registry/docs/serializer-formatter.html#wire-format), which is not enforced by AvroSerializer, the error happens. To fix, we need to align both serializer and deserializer.

**Comment by HenryCaiHaiying** [comment]
Thanks for the diagnose, will you be able to provide a PR to align the
serializer/deserializer?

**Comment by breadpowder** [comment]
Will do.

**Comment by breadpowder** [comment]
Done, please review let me know.
