### ISSUE TITLE
Secor to S3 as parquet error.

### ISSUE THREAD

**Issue by yehoshoua** [pinterest/secor#964]
I try to write Kafka massages to S3 using the S3 messageParser:
**Secor Version 0.26** 
We saw the error in production:

Code Java.
```
package com.pinterest.secor.parser;
import com.pinterest.secor.common.*;
import com.pinterest.secor.message.*;
import net.minidev.json.*;
import org.slf4j.*;
import java.text.*;
import java.util.*;
public class RsdParser extends MessageParser {
    private static final Logger LOG = LoggerFactory.getLogger(RsdParser.class);
    private static final String DATE_FORMAT = "yyyy-MM-dd'T'HH:mm:ss.SSS'Z'";
    private static final String PATH_START = "PATH_START";
    public RsdParser(SecorConfig config) {
        super(config);
    }
    public String[] extractPartitions(Message message) {
        try {
            JSONObject jsonObject = (JSONObject) JSONValue.parse(message.getPayload());
            jsonObject = (JSONObject) JSONValue.parse(jsonObject.get("message").toString().split(" $$$ ")[0]);
            String intermediatePath = ((JSONObject) jsonObject.get("secor")).get("intermediatePath").toString();
            if (intermediatePath.contains(" ")) throw new Exception("path has illegal characters: " + intermediatePath);
            return intermediatePath.split("/");
        }
        catch (Exception e) {
            LOG.warn("could not get partition from message: " + e.getMessage() + ". " + message.getPayload());
            return new String[]{PATH_START, new SimpleDateFormat(DATE_FORMAT).format(new Date())};
        }
    }
}
```
eror code: 
`java.lang.OutOfMemoryError: Java heap space
at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
at org.apache.kafka.common.network.NetworkReceive.readFromReadableChannel(NetworkReceive.java:93)
at kafka.network.BlockingChannel.readCompletely(BlockingChannel.scala:129)
at kafka.network.BlockingChannel.receive(BlockingChannel.scala:120)
at kafka.consumer.SimpleConsumer.liftedTree1$1(SimpleConsumer.scala:99)
at kafka.consumer.SimpleConsumer.kafka$consumer$SimpleConsumer$$sendRequest(SimpleConsumer.scala:83)
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply$mcV$sp(SimpleConsumer.scala:132)
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1$$anonfun$apply$mcV$sp$1.apply(SimpleConsumer.scala:132)
at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply$mcV$sp(SimpleConsumer.scala:131)
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
at kafka.consumer.SimpleConsumer$$anonfun$fetch$1.apply(SimpleConsumer.scala:131)
at kafka.metrics.KafkaTimer.time(KafkaTimer.scala:33)
at kafka.consumer.SimpleConsumer.fetch(SimpleConsumer.scala:130)
at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:108)
at kafka.consumer.ConsumerFetcherThread.fetch(ConsumerFetcherThread.scala:29)
at kafka.server.AbstractFetcherThread.processFetchRequest(AbstractFetcherThread.scala:107)
at kafka.server.AbstractFetcherThread.doWork(AbstractFetcherThread.scala:98)
at kafka.utils.ShutdownableThread.run(ShutdownableThread.scala:63)
`
he's appear few time but create crash of Spark jobs.

Thanks

**Comment by HenryCaiHaiying** [comment]
Parquet conversion does needs lots of memory, did you try to increase the
JVM memory size or try to cut down the number of columns before conversion?

**Comment by dovka** [comment]
Here are the CPU and memory graphs - the crashes happen very regularly, every few days:

Memory - looks like leaking:
![image](https://user-images.githubusercontent.com/22493212/66026124-c9358780-e500-11e9-8bac-a5ff486a7f44.png)

CPU
![secor_CPU](https://user-images.githubusercontent.com/22493212/66026269-26c9d400-e501-11e9-90c7-8f162f385fed.png)

**Comment by dovka** [comment]
Actually it looks like "Secor is leaking memory through DeleteOnExit" #785 issue.

**Comment by yehoshoua** [comment]
any updates ?

**Comment by HenryCaiHaiying** [comment]
This is interesting.  If you can reproduce the problem, can you turn on the debug logging category for FileRegistry.java which will prints out all the files added for deleteOnExit.

It would be interesting to see why there will be so many files added, we have never seen the memory problem on DeleteOnExitHook before and DeleteOnExitHook doesn't have a method to clear the map either.  One suspicion I have is the file size is set to too small (secor.max.file.size.bytes and secor.max.file.age.seconds) so it ends up creating too many files.

**Comment by dovka** [comment]
Henry, 
thank you for answering!

The problem is happening very regularly on our prod env,
see here - 6 times on 3 nodes over the last week:
![image](https://user-images.githubusercontent.com/22493212/82197236-64019b80-9903-11ea-965f-52cf8c978db1.png)

We process about 500K files daily among all 3 nodes, each file about 100K in size - does it qualify as small?

I'll try to enable debugging and keep you posted.
It might take some time since this is production.

**Comment by HenryCaiHaiying** [comment]
How much memory do you configure for the java process?  From https://github.com/pinterest/secor/issues/785, looks like DeleteOnExitHook took 260MB which is not that big.   If you create 500K files and assume each file path takes 100 bytes, you will register 50MB each day with DeleteOnExitHook

**Comment by dovka** [comment]
Wow... this is an embarrassment :)
We don't set the max heap size....
Thank you for pointing it out!

Se we are running on the defaults:

java -XX:+PrintFlagsFinal -version | grep -iE 'HeapSize|PermSize|ThreadStackSize'
     intx CompilerThreadStackSize                   = 0                                   {pd product}
    uintx ErgoHeapSizeLimit                         = 0                                   {product}
    uintx HeapSizePerGCThread                       = 87241520                            {product}
    uintx InitialHeapSize                          := 132120576                           {product}
    uintx LargePageHeapSizeThreshold                = 134217728                           {product}
    uintx MaxHeapSize                              := 2090860544                          {product}
     intx ThreadStackSize                           = 1024                                {pd product}
     intx VMThreadStackSize                         = 1024                                {pd product}
java version "1.8.0_131"
Java(TM) SE Runtime Environment (build 1.8.0_131-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.131-b11, mixed mode)

We run secor on 8G instances, so I can set max heap to at least 4G

![image](https://user-images.githubusercontent.com/22493212/82293113-b8188880-99b4-11ea-9525-6a8e01a37701.png)

I will post in a a few days if this improved the situation (e.g. if we had crashes)
Thank you again for the advice!

**Comment by dovka** [comment]
Great news - a week without a single crash, on all three nodes.
The memory usage however grows steadily. So far I'm afraid that we just pushed away how frequently the crash happens. I will update the ticket in a few weeks once it is clear.

**Comment by HenryCaiHaiying** [comment]
Will you be able to do some heap dump or just object counts (which is less intrusive) on your system?  I think it's more likely the parquet side's memory consumption is far more than secor's

**Comment by dovka** [comment]
Henry, thank you - how do I count objects?
I want to have some non-intrusive metric that I can run periodically.
Currently (after maxmem fix) we have crashes not so often, but each instance still crashes between 6 and 15 days.
![image](https://user-images.githubusercontent.com/22493212/86807839-e5afb300-c082-11ea-9a06-62c5db863c23.png)

**Comment by HenryCaiHaiying** [comment]
Try jmap: https://docs.oracle.com/javase/7/docs/technotes/tools/share/jmap.html, but not actually use -dump to generate the heap dump which will takes too much time.  Use '-histo' to generate the histogram of the heap which will include number of objects for each class, this is much faster.

**Comment by dovka** [comment]
Thank you Henry!

here is the /opt/jdk/bin/jmap -histo 20 for the 13-day java secor process (soon-to-die)
[secor_jmap_histo_13days.log](https://github.com/pinterest/secor/files/4899402/secor_jmap_histo_13days.log)

and this is just a 2-day process (for comparison)
[secor_jmap_histo_2days.log](https://github.com/pinterest/secor/files/4899407/secor_jmap_histo_2days.log)

Please let me know if some particular count is interesting to you - I can count it over time on the same process.

**Comment by HenryCaiHaiying** [comment]
There are lots of character arrays which might come from String (6M char
arrays taking 2.8GB averaging 475 bytes each array), but it's not
conclusive to say it's from delteOnExit()'s hash map of file names.  For
DeleteOnExit, the map storage is the HashMap (the map variable in
LinkedHashSet), but I only saw 46K HashMap$Node, it's way less than 6M char
arrays

 num     #instances         #bytes  class name

----------------------------------------------

   1:       6007380     2858647544  [C

   2:       5387565      215502600  java.util.LinkedHashMap$Entry

   3:       1041602      161973168  [B

   4:       5822839      139748136  java.lang.String

   5:        140865      132649984  [I

   6:         46626       37827656  [Ljava.util.HashMap$Node;

**Comment by HenryCaiHaiying** [comment]
The other observation: the number of char arrays (6M) is very close to the
number of LinkedHashMap$Entry (5.3M), it looks like the memory consumption
is from a LinkedHashMap of String (either String is the key or the value),
but File.deleteOnExit() is using HashMap, not LinkedHashMap

**Comment by HenryCaiHaiying** [comment]
Correction: I traced the File.deleteOnExit() once more, looks like the map
variable inside HashSet.java was initialized with LinkedHashMap (not the
regular HashMap), then it makes sense now.  The 5.38M LinkedHashMap$Entry
entries is probably related to DeleteOnExit(), we have accumulated 5.38M
file names.

**Comment by HenryCaiHaiying** [comment]
Maybe this PR: https://github.com/pinterest/secor/pull/1449 can fix the
problem.

**Comment by HenryCaiHaiying** [comment]
@dovka Please try the PR: #1449

**Comment by dovka** [comment]
Thank you Henry!
Our third party usage policy requires us to use official releases.
For which release do you guys plan to pack PR: #1449?
When you think it will be ready?

**Comment by HenryCaiHaiying** [comment]
David, I just cut a new release v0.29, it might take a day or two to show
up in maven central.   You can use that release

**Comment by dovka** [comment]
Henry - thank you so much!
I will push the release to prod and will let you know how it worked.
(should have a picture in couple of weeks or so)
