### ISSUE TITLE
Strange behavior around folders (broken exactly-once guarantee)

### ISSUE THREAD

**Issue by qix** [pinterest/secor#97]
Hi,

I've been fighting to get secor working smoothly on our side but still keep hitting further issues. At first the line-delimited format was missing data (previous issue) so I switched over to sequence files which seem to be more reliable.

I have an issue as the files move to a new folder however, where the filename is not the starting offset, but rather the same filename as the final file in the previous bucket. I've been renaming them successfully for a while, but today I hit upon a set of files that looked like this:

```
/seq/counter/offset=4000000/1_0_00000000000004978500 contains: 4978500 => 4992667 (a)
/seq/counter/offset=4000000/1_0_00000000000004992668 contains: 4992668 => 4999999 (b)
/seq/counter/offset=5000000/1_0_00000000000004920756 contains: 5000000 => 5059705 (c)
/seq/counter/offset=5000000/1_0_00000000000004992668 contains: 5000000 => 5014068 (d)
/seq/counter/offset=5000000/1_0_00000000000005014069 contains: 5014069 => 5027951 (e)
```

To me that's a fundamental break in the guarentee's secor provides (exactly once), which seems to be related to a bug in the filenames. The set of files a/b/d/e would be correct, and I imagine (d) would have overwritten (c) if they were correctly named `1_0_00000000000005000000`, but because of the naming both files were present.

**Comment by pgarbacki** [comment]
Hi @qix 

is is perfectly normal for the offset in the filename not to be the offset of the first message in that file. Filename offsets correspond to commit points and a single commit point may span multiple partitions (offset= directories).

Having that said, data duplication is not normal. Looking at the listing you included, /seq/counter/offset=5000000/1_0_00000000000004920756 is out of place.

Is there any way to reproduce this behavior?

Could you share more data (creation/modification times for those files, secor logs, etc.)?
