### ISSUE TITLE
secor.max.file.size.bytes does not apply for JsonORCFileReaderWriterFactory

### ISSUE THREAD

**Issue by zjiawei3** [pinterest/secor#971]
Hi team, we recently ran into an issue with Kafka traffic burst causing message lag on secor, and we decided to use secor.max.file.size.bytes in parallel with secor.max.file.age.seconds to handle the burst. Here is our relevant config entries:

...

# To set a custom file extension set this to a valid file suffix, such as
# '.gz', '.part', etc.
secor.file.extension=.snappy.orc

secor.file.reader.writer.factory=com.pinterest.secor.io.impl.JsonORCFileReaderWriterFactory

...

# 100MB
secor.max.file.size.bytes=100000000

# 30 minutes
secor.max.file.age.seconds=1800

# Number of consumer threads per Secor process.
secor.consumer.threads=4

# Consumption rate limit enforced at the process level (not a consumer-thread level).
secor.messages.per.second=5000000

But with this config applied, we noticed there are still S3 files over 100MB during traffic burst. Does secor.max.file.size.bytes work for JsonORCFileReaderWriterFactory?
Thanks!

**Comment by HenryCaiHaiying** [comment]
How much bigger than 100MB?  Secor checks the file periodically so it's
possible the file goes over a little over 100MB.
