### ISSUE TITLE
Skipping Tests (MVN_OPTS=-DskipTests=true)

### ISSUE THREAD

**Issue by suminb** [pinterest/secor#973]
I've noticed every command in `Makefile` is set up to skip tests by `-DskipTests=true`. It makes sense for non-testing `mvn` commands such as `build` and `dependency_tree`, but I believe the `unit` command should not skip tests.

```
unit:
	@mvn test $(MVN_OPTS) -P $(MVN_PROFILE)
```

As `$MVN_OPTS` contains `-DskipTests=true` flag `make unit` skips all tests, as clearly shown in [Travis CI build logs](https://travis-ci.org/pinterest/secor/jobs/589934852).

```
[INFO] Tests are skipped.
```

Another thing to point out is that `$MVN_OPTS` already contains `$MVN_PROFILE` so the tailing part (` -P $(MVN_PROFILE)`) seems redundant.

I was wondering whether this is intentional, or it is something I could fix and send a PR.

**Comment by HenryCaiHaiying** [comment]
Please feel free to submit a PR for this

**Comment by suminb** [comment]
#979 resolves this.
