### ISSUE TITLE
Secor stops processing new messages

### ISSUE THREAD

**Issue by jimymodi** [pinterest/secor#981]
We are running secor 0.27 in production for past 6-7 months. The message in rate of the topic secor is subscribed to is 1.2K/s avg and min-max of 0.3K - 2K. 
Everything was running fine till yesterday. Yesterday all of a sudden secor stops processing messages. There is nothing in the logs. However, when I restart the java process, it does start processing for very few second and then again stops. 
![image](https://user-images.githubusercontent.com/415224/65831674-03711000-e2da-11e9-8075-bf2a8bedb482.png)
The small towers are the time when I restarted the java process.
Here I am attaching INFO log of whole one cycle where it starts consuming for few seconds and then goes idle. I have also attached the config file used for secor.

The Kafka version we are using is `1.0.0` and ZK version is `3.4.10`

I strange thing I noticed is with latency of one ZK node. We have 5 ZK nodes, and out of that one is showing very high max latency as below.
```
ZK1 follower Latency min/avg/max: 0/0/49
ZK2 follower Latency min/avg/max: 0/0/787
ZK3 follower Latency min/avg/max: 0/0/7
ZK4 follower Latency min/avg/max: 0/0/125
**ZK5 leader Latency min/avg/max: 0/0/4929**
```

Could this be the issue ?

Log [logs-insights-results.txt](https://github.com/pinterest/secor/files/3666689/logs-insights-results.txt)
Config 
[secor.common.properties.txt](https://github.com/pinterest/secor/files/3666694/secor.common.properties.txt)

Does anyone see something fishy here ?

**Comment by jimymodi** [comment]
We restarted the high latency `ZK5` node and now latency of all node is between 2-24.

**Comment by HenryCaiHaiying** [comment]
Was the issue resolved by bouncing ZK nodes?
